import os
from building import *

cwd = GetCurrentDir()
bsp_root = os.path.dirname(cwd)

# add general drivers; rt_board_init provides strong rt_hw_board_init for ArduPilot link
# drv_mpu.c needs HAL_MPU_* from stm32h7xx_hal_cortex.c (provided by stm32h7_hal_driver package)
src = Split('''
board.c
rt_board_init.c
drv_mpu.c
CubeMX_Config/Src/stm32h7xx_hal_msp.c
''')

path = [cwd]
path += [os.path.join(cwd, 'CubeMX_Config', 'Inc')]

# BSP-local packages: add Include paths for stm32h7xx.h, HAL (board.c needs RCC_OscInitTypeDef etc.)
pkgs_dir = os.path.join(bsp_root, 'packages')
if os.path.isdir(pkgs_dir):
    for pkg_inc in [
        os.path.join(pkgs_dir, 'CMSIS-Core-latest', 'Include'),
        os.path.join(pkgs_dir, 'stm32h7_cmsis_driver-latest', 'Include'),
        os.path.join(pkgs_dir, 'stm32h7_hal_driver-latest', 'Inc'),
    ]:
        if os.path.isdir(pkg_inc):
            path += [pkg_inc]

# STM32H743xx || STM32H750xx || STM32F753xx
# You can select chips from the list above
CPPDEFINES = ['STM32H743xx']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)
list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
