from building import *

cwd = GetCurrentDir()
common_dir = os.path.normpath(os.path.join(cwd, '..', '..', '_common'))
src = Glob('*.c')
src += Glob(os.path.join(common_dir, 'test_stubs.c'))
CPPPATH = [cwd, common_dir]

group = DefineGroup('test_l0_boot', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
