/* rtconfig.h — generated from .config */
#ifndef RTCONFIG_H
#define RTCONFIG_H

#define SOC_STM32F767ZI
#define BOARD_STM32F767_NUCLEO
#define RT_NAME_MAX 12
#define RT_CPUS_NR 1
#define RT_ALIGN_SIZE 8
#define RT_THREAD_PRIORITY_32
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 1000
#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HOOK
#define RT_HOOK_USING_FUNC_PTR
#define RT_USING_IDLE_HOOK
#define RT_IDLE_HOOK_LIST_SIZE 4
#define IDLE_THREAD_STACK_SIZE 256
#define RT_TIMER_THREAD_PRIO 4
#define RT_TIMER_THREAD_STACK_SIZE 2048
#define RT_USING_DEBUG
#define RT_DEBUGING_ASSERT
#define RT_DEBUGING_COLOR
#define RT_DEBUGING_CONTEXT
#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
#define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE
#define RT_USING_MEMPOOL
#define RT_USING_SMALL_MEM
#define RT_USING_SMALL_MEM_AS_HEAP
#define RT_USING_HEAP
#define RT_USING_DEVICE
#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE 128
#define RT_CONSOLE_DEVICE_NAME "uart7"
#define RT_USING_CONSOLE_OUTPUT_CTL
#define RT_VER_NUM 0x50201
#define RT_BACKTRACE_LEVEL_MAX_NR 32
#define RT_USING_CACHE
#define RT_USING_HW_ATOMIC
#define RT_USING_CPU_FFS
#define ARCH_ARM
#define ARCH_ARM_CORTEX_M
#define ARCH_ARM_CORTEX_M7
#define RT_USING_COMPONENTS_INIT
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 65536
#define RT_MAIN_THREAD_PRIORITY 10
#define RT_USING_MSH
#define RT_USING_FINSH
#define FINSH_USING_MSH
#define FINSH_THREAD_NAME "tshell"
#define FINSH_THREAD_PRIORITY 20
#define FINSH_THREAD_STACK_SIZE 4096
#define FINSH_USING_HISTORY
#define FINSH_HISTORY_LINES 5
#define FINSH_USING_SYMTAB
#define FINSH_CMD_SIZE 80
#define MSH_USING_BUILT_IN_COMMANDS
#define FINSH_USING_DESCRIPTION
#define FINSH_ARG_MAX 10
#define FINSH_USING_OPTION_COMPLETION
#define RT_USING_DFS
#define DFS_USING_POSIX
#define DFS_USING_WORKDIR
#define DFS_FD_MAX 16
#define RT_USING_DFS_V1
#define DFS_FILESYSTEMS_MAX 4
#define DFS_FILESYSTEM_TYPES_MAX 4
#define RT_USING_DFS_ELMFAT
#define RT_DFS_ELM_CODE_PAGE 437
#define RT_DFS_ELM_WORD_ACCESS
#define RT_DFS_ELM_USE_LFN_3
#define RT_DFS_ELM_USE_LFN 3
#define RT_DFS_ELM_LFN_UNICODE_0
#define RT_DFS_ELM_LFN_UNICODE 0
#define RT_DFS_ELM_MAX_LFN 255
#define RT_DFS_ELM_DRIVES 2
#define RT_DFS_ELM_MAX_SECTOR_SIZE 4096
#define RT_DFS_ELM_REENTRANT
#define RT_DFS_ELM_MUTEX_TIMEOUT 3000
#define RT_USING_DFS_DEVFS
#define RT_USING_DEVICE_IPC
#define RT_UNAMED_PIPE_NUMBER 64
#define RT_USING_SERIAL
#define RT_USING_SERIAL_V1
#define RT_SERIAL_USING_DMA
#define RT_SERIAL_RB_BUFSZ 64
#define RT_USING_I2C
#define RT_USING_PWM
#define RT_USING_SDIO
#define RT_USING_BLK
#define RT_USING_SPI
#define BSP_USING_SPI
#define BSP_USING_SPI1
#define BSP_USING_SPI2
#define BSP_USING_SPI4
#define RT_USING_I2C_BITOPS
#define RT_USING_PIN
#define RT_USING_CHERRYUSB
#define RT_CHERRYUSB_DEVICE
#define RT_CHERRYUSB_DEVICE_SPEED_FS
#define RT_CHERRYUSB_DEVICE_DWC2_ST
#define RT_CHERRYUSB_DEVICE_CDC_ACM
#define RT_CHERRYUSB_DEVICE_CDC_ACM_CHARDEV
#define RT_CHERRYUSB_DEVICE_TEMPLATE_CDC_ACM_CHARDEV
#define RT_LIBC_USING_LIGHT_TZ_DST
#define RT_LIBC_TZ_DEFAULT_HOUR 8
#define RT_LIBC_TZ_DEFAULT_MIN 0
#define RT_LIBC_TZ_DEFAULT_SEC 0
#define PKG_USING_CMSIS_CORE
#define PKG_CMSIS_CORE_PATH "/packages/system/CMSIS/CMSIS-Core"
#define PKG_USING_CMSIS_CORE_LATEST_VERSION
#define PKG_CMSIS_CORE_VER "latest"
#define PKG_USING_STM32F7_HAL_DRIVER
#define PKG_STM32F7_HAL_DRIVER_PATH "/packages/peripherals/hal-sdk/stm32/stm32f7_hal_driver"
#define PKG_USING_STM32F7_HAL_DRIVER_LATEST_VERSION
#define PKG_STM32F7_HAL_DRIVER_VER "latest"
#define PKG_USING_STM32F7_CMSIS_DRIVER
#define PKG_STM32F7_CMSIS_DRIVER_PATH "/packages/peripherals/hal-sdk/stm32/stm32f7_cmsis_driver"
#define PKG_USING_STM32F7_CMSIS_DRIVER_LATEST_VERSION
#define PKG_STM32F7_CMSIS_DRIVER_VER "latest"
#define SOC_FAMILY_STM32
#define SOC_SERIES_STM32F7
#define BOARD_SERIES_STM32_NUCLEO_144
#define BSP_USING_USB_TO_USART
#define BSP_USING_USB_DEVICE
#define BSP_USING_GPIO
#define BSP_USING_UART
#define BSP_STM32_UART_V1_TX_TIMEOUT 4000
#define BSP_USING_UART3
#define BSP_USING_UART7
#define BSP_USING_SDIO


/* === Auto-enabled from hwdef.dat === */
#define RT_USING_USART2
#define BSP_USING_UART2
#define RT_USING_USART3
#define BSP_USING_UART3
#define RT_USING_USART1
#define BSP_USING_UART1
#define RT_USING_UART4
#define BSP_USING_UART4
#define RT_USING_USART6
#define BSP_USING_UART6
#define RT_USING_UART7
#define BSP_USING_UART7
#define RT_USING_SPI1
#define RT_USING_SPI4
#define BSP_SPI4_RX_USING_DMA
#define BSP_SPI4_TX_USING_DMA
#define RT_USING_SPI2
#define BSP_SPI2_RX_USING_DMA
#define BSP_SPI2_TX_USING_DMA
#define RT_USING_I2C
#define RT_USING_I2C_BITOPS
#define BSP_USING_I2C3
#define BSP_I2C3_SCL_PIN 119
#define BSP_I2C3_SDA_PIN 120
#define BSP_USING_I2C1
#define BSP_I2C1_SCL_PIN 24
#define BSP_I2C1_SDA_PIN 25
#define BSP_USING_I2C2
#define BSP_I2C2_SCL_PIN 81
#define BSP_I2C2_SDA_PIN 80
#define BSP_USING_I2C4
#define BSP_I2C4_SCL_PIN 94
#define BSP_I2C4_SDA_PIN 95
#define RT_USING_PWM
#define RT_USING_SDIO
#define BSP_USING_USB_DEVICE
#endif /* RTCONFIG_H */
