/*
 * RT-Thread board init for AP_HAL_RTT — GENERIC template.
 * All board-specific configuration comes from hwdef.h macros
 * generated by rtt_hwdef.py from hwdef.dat.
 *
 * GPIO power pins: HAL_GPIO_<LABEL>_PIN / HAL_GPIO_<LABEL>_INIT
 * SPI attach:      HAL_RTT_SPI_ATTACH_LIST
 * Flash origin:    FLASH_ORIGIN
 */
#include <rtthread.h>
#include <rtdevice.h>
#include <stdbool.h>
#include "board.h"
#include "drv_gpio.h"

#ifdef BSP_USING_SPI
#include "drv_spi.h"
#endif

#include "hwdef.h"

/* SPI Low-Level DMA driver (STM32F7 only) */
#ifdef SOC_SERIES_STM32F7
#include "drv_spi_lld.h"
#endif

extern void usb_lld_poll_rtt(void);
extern bool usb_lld_is_configured_rtt(void);

extern int rt_hw_pin_init(void);
extern int rt_hw_usart_init(void);
extern void __libc_init_array(void);
extern void rt_hw_systick_init(void);

#if defined(BSP_USING_SPI) && defined(HAL_RTT_SPI_ATTACH_LIST)
struct spi_attach_entry {
    const char *bus_name;
    const char *dev_name;
    rt_base_t cs_pin;
};

static const struct spi_attach_entry _spi_attach_table[] = {
#define HAL_RTT_SPI_ATTACH_ROW(busnum, busname, devname, cs) \
    {busname, devname, cs}
    HAL_RTT_SPI_ATTACH_FOREACH(HAL_RTT_SPI_ATTACH_ROW)
#undef HAL_RTT_SPI_ATTACH_ROW
};

static void _spi_device_init(void)
{
    rt_kprintf("[SPI-INIT] Starting SPI device attachment\n");
    for (unsigned i = 0; i < sizeof(_spi_attach_table) / sizeof(_spi_attach_table[0]); i++) {
        if (rt_device_find(_spi_attach_table[i].bus_name) == RT_NULL) {
            rt_kprintf("[SPI-ATTACH] skip %s -> %s: bus %s not found\n",
                       _spi_attach_table[i].bus_name,
                       _spi_attach_table[i].dev_name,
                       _spi_attach_table[i].bus_name);
            continue;
        }
        rt_err_t ret = rt_hw_spi_device_attach(_spi_attach_table[i].bus_name,
                                _spi_attach_table[i].dev_name,
                                _spi_attach_table[i].cs_pin);
        rt_kprintf("[SPI-ATTACH] %s -> %s cs=0x%x ret=%d\n",
                   _spi_attach_table[i].bus_name,
                   _spi_attach_table[i].dev_name,
                   (unsigned)_spi_attach_table[i].cs_pin, (int)ret);
        /* RTT's rt_spi_bus_attach_device_cspin() only calls rt_pin_mode(OUTPUT)
         * but does NOT drive CS HIGH (inactive).  All CS pins default to LOW
         * (asserted), causing MISO bus contention when multiple devices share
         * the same SPI bus (e.g. 5 IMUs on SPI1).  Drive CS HIGH here. */
        if (ret == RT_EOK && _spi_attach_table[i].cs_pin != PIN_NONE) {
            rt_pin_write(_spi_attach_table[i].cs_pin, PIN_HIGH);
        }
    }
    rt_kprintf("[SPI-INIT] SPI device attachment complete\n");
}
#endif

static void _mpu_config(void)
{
    __DMB();
    MPU->CTRL = 0;

    /*
     * Region 0: All SRAM (DTCM + SRAM1 + SRAM2), base 0x20000000, 1MB
     * Normal, Write-Through No Write-Allocate, NON-Shareable, Full Access.
     * S=0 forces local exclusive monitor for ldrex/strex, avoiding
     * STM32F7 AXI bus global-monitor PRECISERR on SRAM exclusive access.
     */
    MPU->RNR  = 0;
    MPU->RBAR = 0x20000000U;
    MPU->RASR = (0U  << 28) |  /* XN=0 */
                (3U  << 24) |  /* AP=011 full access */
                (0U  << 19) |  /* TEX=000 */
                (0U  << 18) |  /* S=0 non-shareable */
                (1U  << 17) |  /* C=1 cacheable */
                (0U  << 16) |  /* B=0 not bufferable */
                (0U  <<  8) |  /* SRD=0 */
                (19U <<  1) |  /* SIZE=19 → 1MB */
                (1U  <<  0);   /* ENABLE */

    /*
     * Region 1: Peripheral space (0x40000000, 512MB)
     * Device Shareable - matches ARMv7-M default memory map.
     * TEX=010, C=0, B=1, S=1 -> Device Shareable (ARM ARM B3-572).
     * ChibiOS uses PRIVDEFENA default map instead of explicit region.
     */
    MPU->RNR  = 1;
    MPU->RBAR = 0x40000000U;
    MPU->RASR = (1U  << 28) |  /* XN=1 no exec */
                (3U  << 24) |  /* AP=011 full access */
                (2U  << 19) |  /* TEX=010 = Device */
                (1U  << 18) |  /* S=1 shareable */
                (0U  << 17) |  /* C=0 */
                (1U  << 16) |  /* B=1 (required for Device Shareable) */
                (0U  <<  8) |  /* SRD=0 */
                (28U <<  1) |  /* SIZE=28 → 512MB */
                (1U  <<  0);   /* ENABLE */

    /*
     * Region 2: .sram1_bss DMA buffers (e.g. SDIO cache_buf) — non-cacheable.
     * Linker places .sram1_bss at 0x20020000; cover full 64KB SRAM1 tail.
     * Higher region number overrides Region 0 for this range.
     */
    MPU->RNR  = 2;
    MPU->RBAR = 0x20020000U;
    MPU->RASR = (0U  << 28) |  /* XN=0 */
                (3U  << 24) |  /* AP=011 full access */
                (1U  << 19) |  /* TEX=001 normal non-cacheable */
                (0U  << 18) |  /* S=0 */
                (0U  << 17) |  /* C=0 */
                (0U  << 16) |  /* B=0 */
                (0U  <<  8) |  /* SRD=0: all sub-regions enabled */
                (15U <<  1) |  /* SIZE=15 → 64KB */
                (1U  <<  0);   /* ENABLE */

    MPU->CTRL = MPU_CTRL_PRIVDEFENA_Msk | MPU_CTRL_ENABLE_Msk;
    __DSB();
    __ISB();
}

static void _fpu_context_init(void)
{
#if defined (__VFP_FP__) && !defined(__SOFTFP__)
    /*
     * Lua scripting mixes hard-float code with frequent RT-Thread context
     * switches. Disable lazy stacking so exception entry always materializes
     * the low FPU frame on the owning thread stack instead of deferring via
     * FPCAR/LSPACT, which has been triggering INVSTATE during mixed FPU/non-FPU
     * thread switches on CUAV V5 bring-up.
     */
    FPU->FPCCR |= FPU_FPCCR_ASPEN_Msk;
    FPU->FPCCR &= ~FPU_FPCCR_LSPEN_Msk;
    __DSB();
    __ISB();
#endif
}

/*
 * SPI LLD contexts for STM32F7 DMA-backed buses.
 * Registered before rt_components_board_init() so that rt_hw_spi_init()
 * (INIT_BOARD_EXPORT) finds them during rt_hw_spi_bus_init().
 */
#ifdef SOC_SERIES_STM32F7
#if defined(BSP_USING_SPI1) && defined(BSP_SPI1_TX_USING_DMA) && defined(BSP_SPI1_RX_USING_DMA)
static spi_lld_bus_t s_spi1_lld = {
    .spi     = SPI1,
    .dma_rx  = SPI1_RX_DMA_INSTANCE,
    .dma_tx  = SPI1_TX_DMA_INSTANCE,
    .ch_rx   = SPI1_RX_DMA_CHANNEL,
    .ch_tx   = SPI1_TX_DMA_CHANNEL,
    .irq_rx  = SPI1_RX_DMA_IRQ,
    .irq_tx  = SPI1_TX_DMA_IRQ,
};
#endif

#if defined(BSP_USING_SPI4) && defined(BSP_SPI4_TX_USING_DMA) && defined(BSP_SPI4_RX_USING_DMA)
static spi_lld_bus_t s_spi4_lld = {
    .spi     = SPI4,
    .dma_rx  = SPI4_RX_DMA_INSTANCE,
    .dma_tx  = SPI4_TX_DMA_INSTANCE,
    .ch_rx   = SPI4_RX_DMA_CHANNEL,
    .ch_tx   = SPI4_TX_DMA_CHANNEL,
    .irq_rx  = SPI4_RX_DMA_IRQ,
    .irq_tx  = SPI4_TX_DMA_IRQ,
};
#endif

static void _spi_lld_board_init(void)
{
#if defined(BSP_USING_SPI1) && defined(BSP_SPI1_TX_USING_DMA) && defined(BSP_SPI1_RX_USING_DMA)
    spi_lld_register(&s_spi1_lld);
    spi_lld_bus_init(&s_spi1_lld);
    /*
     * Do NOT enable SPI1 DMA NVIC here (same rule as SPI4).
     * stm32_spi_init() enables IRQ after spi_bus_obj[SPI1].lld attach.
     */
#endif
#if defined(BSP_USING_SPI4) && defined(BSP_SPI4_TX_USING_DMA) && defined(BSP_SPI4_RX_USING_DMA)
    spi_lld_register(&s_spi4_lld);
    spi_lld_bus_init(&s_spi4_lld);
    /*
     * Do NOT enable SPI4 DMA NVIC here.
     * spi_bus_obj[x].lld is only attached later in rt_hw_spi_init()
     * during rt_components_board_init(). Enabling the IRQs before that
     * allows stale DMA interrupts to hit the HAL fallback path with an
     * uninitialized handle/context, which can HardFault early in boot.
     *
     * Leave the streams quiesced here; enable NVIC only after the SPI
     * bus object has attached the LLD context.
     */
#endif
}
#endif /* SOC_SERIES_STM32F7 */

/* ──────────────────────────────────────────────
 *  IWDG early feed — Layer 0 foundation.
 *  Hardware watchdog (if enabled by option bytes)
 *  starts counting from reset with ~512ms timeout.
 *
 *  Strategy: feed NOW, don't reconfigure PR/RLR
 *  (LSI-domain PVU/RVU sync can hang early in boot
 *   before clock init).  The 512ms window is enough
 *   for board init + scheduler startup; after that,
 *   ap_rtt_iwdg_init() in HAL_RTT::run() extends
 *   to ~10s and sets up periodic feeding.
 *
 *  CMSIS struct access — uses IWDG_TypeDef from
 *  stm32f7xx.h (no HAL dependency).
 * ────────────────────────────────────────────── */
static void _iwdg_early_feed(void)
{
    /* Just reload the counter; no PR/RLR writes.
     * 0xAAAA is the refresh key — doesn't need unlock. */
    IWDG->KR = 0xAAAAU;
}

static void _iwdg_reconfig(void)
{
    /* Reconfigure IWDG to longer timeout (~10s).
     * Called AFTER clock init, when LSI is stable
     * and APB bus interface is fully operational.
     * NO rt_kprintf here — console not yet initialized. */
    IWDG->KR = 0x5555U;
    IWDG->PR = 6U;
    for (volatile int i = 0; i < 100000 && (IWDG->SR & IWDG_SR_PVU); i++) { }
    IWDG->KR = 0x5555U;
    IWDG->RLR = 1250U;
    for (volatile int i = 0; i < 100000 && (IWDG->SR & IWDG_SR_RVU); i++) { }
    IWDG->KR = 0xAAAAU;
}

void rt_hw_board_init(void)
{
    /* Layer 0: IWDG watchdog — feed immediately before any init that
     * may take >512ms (the default hardware watchdog timeout).
     * PR/RLR reconfig deferred to after clock init (see _iwdg_reconfig below). */
    _iwdg_early_feed();

    rt_kprintf("[BOARD-INIT] Starting board initialization\n");
#ifdef FLASH_ORIGIN
    SCB->VTOR = FLASH_ORIGIN;
#else
    SCB->VTOR = 0x08008000U;
#endif

    _mpu_config();
    _fpu_context_init();
    SCB_EnableICache();
    // SCB_EnableDCache();  // Disabled: USB DWC2 DMA coherency issues on STM32F7

    /* Enable SWD debug interface in all low-power modes (WFI/STOP/STANDBY).
     * Without this, ST-Link connection drops when the chip enters WFI idle.
     * CUAV V5 NRST pin is not connected, so SWD must stay alive. */
    DBGMCU->CR |= DBGMCU_CR_DBG_SLEEP | DBGMCU_CR_DBG_STOP | DBGMCU_CR_DBG_STANDBY;

    /* Freeze IWDG counter when debugger halts the CPU.
     * Without this, IWDG continues running during debug → ~2s timeout → reset →
     * debug connection drops. */
    DBGMCU->APB1FZ |= DBGMCU_APB1_FZ_DBG_IWDG_STOP;

    /* Clock init: pure CMSIS register writes (no HAL) */
    NVIC_SetPriorityGrouping(3U);  /* PRIGROUP=3 → 4-bit preemption */

    rtt_clock_init();
    rtt_enable_peripheral_clocks();

    /* IWDG reconfig to ~10s — after clock/peripheral init so APB bus
     * interface is stable and LSI-domain sync completes reliably. */
    _iwdg_reconfig();

    rt_hw_systick_init();
    rt_hw_pin_init();
    rt_hw_usart_init();

#ifdef SOC_SERIES_STM32F7
    /* UART7 hardware telemetry lane for closed-loop agents (independent of console). */
    extern void rtt_ctl_uart_hw_init(void);
    extern void rtt_ctl_hw_write(const char *s);
    rtt_ctl_uart_hw_init();
    rtt_ctl_hw_write("[BOARD-INIT] uart7 hw lane up\r\n");
#endif

    /* GPIO power pins moved to _sensor_power_init (INIT_PREV_EXPORT) —
     * DCache interference causes MODER writes at this early stage to be
     * lost when HAL_SPI_MspInit later does read-modify-write on the same
     * GPIO port (e.g. SPI4 HAL_GPIO_Init on GPIOE clobbers PE3). */

#ifdef RT_USING_HEAP
    rt_system_heap_init(HEAP_BEGIN, HEAP_END);
#endif

#ifdef RT_USING_CONSOLE
    rt_console_set_device(RT_CONSOLE_DEVICE_NAME);
#endif

    /* Register SPI LLD contexts before rt_components_board_init() so that
     * rt_hw_spi_init() (INIT_BOARD_EXPORT) finds them. */
#ifdef SOC_SERIES_STM32F7
#if (defined(BSP_USING_SPI1) && defined(BSP_SPI1_TX_USING_DMA) && defined(BSP_SPI1_RX_USING_DMA)) || \
    (defined(BSP_USING_SPI4) && defined(BSP_SPI4_TX_USING_DMA) && defined(BSP_SPI4_RX_USING_DMA))
    _spi_lld_board_init();
#endif
#endif

    rt_kprintf("[BOARD-INIT] Calling rt_components_board_init()\n");
#ifdef RT_USING_COMPONENTS_INIT
    rt_components_board_init();
#endif

        /* 强制重新使能GPIOE时钟 — AHB1ENR |= GPIOEEN 在 stm32f7_clock_ll.c 中可能因
         * D-Cache/同步问题未生效。加上DSB屏障保证写管道清空。 */
        RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;
        __DSB();
        __ISB();
        (void)RCC->AHB1ENR;  /* 强制读，保证写管道清空 */

        /* Sensor power PE3 re-apply (SPI4 HAL init can clobber it) */
    {
        volatile uint32_t *moder = (volatile uint32_t *)0x40021000; /* GPIOE */
        uint32_t m = *moder;
        m &= ~(3U << 6);   /* clear PE3 MODER bits */
        m |= (1U << 6);    /* set OUTPUT mode */
        *moder = m;
        /* Also ensure ODR[3] = HIGH */
        *(volatile uint32_t *)0x40021014 |= (1U << 3);
    }

    /*
     * SPI1 GPIO early init — configure PG11(SCK)/PA6(MISO)/PD7(MOSI) as AF5.
     * Must happen here (before SPI/IMU probe in setup()) rather than lazily
     * in SPIDevice.cpp _spi1_gpio_init(), because the lazy init is only
     * triggered on first SPI transfer — setup() probes the IMU before that.
     *
     * Pinout (CUAV V5, confirmed from ChibiOS fmuv5):
     *   PG11=SCK(AF5), PA6=MISO(AF5), PD7=MOSI(AF5)
     *   NOT PA5/PA7 (those are FMU_CAP1 and HEATER_EN respectively!)
     */
#ifdef BSP_USING_SPI1
    {
        RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIODEN | RCC_AHB1ENR_GPIOGEN;
        (void)RCC->AHB1ENR;
        /* PG11 SCK: MODE=AF(10), AF=AF5(0101) */
        GPIOG->MODER = (GPIOG->MODER & ~(3U << 22)) | (2U << 22);
        GPIOG->AFR[1] = (GPIOG->AFR[1] & ~(0xFU << 12)) | (5U << 12);
        GPIOG->OSPEEDR = (GPIOG->OSPEEDR & ~(3U << 22)) | (3U << 22);
        /* PA6 MISO: MODE=AF(10), AF=AF5(0101) */
        GPIOA->MODER = (GPIOA->MODER & ~(3U << 12)) | (2U << 12);
        GPIOA->AFR[0] = (GPIOA->AFR[0] & ~(0xFU << 24)) | (5U << 24);
        GPIOA->OSPEEDR = (GPIOA->OSPEEDR & ~(3U << 12)) | (3U << 12);
        /* PD7 MOSI: MODE=AF(10), AF=AF5(0101) */
        GPIOD->MODER = (GPIOD->MODER & ~(3U << 14)) | (2U << 14);
        GPIOD->AFR[0] = (GPIOD->AFR[0] & ~(0xFU << 28)) | (5U << 28);
        GPIOD->OSPEEDR = (GPIOD->OSPEEDR & ~(3U << 14)) | (3U << 14);

        /*
         * SPI1 CS — drive all inactive (HIGH) before IMU/SPI probe.
         * ChibiOS fmuv5 SPI1 CS: PF2(ICM20689), PF3(ICM20602), PF4(BMI055_G),
         * PG10(BMI055_A).  Also PH5(AUXMEM_CS), PF11(SPARE/ICM42688 on RTT).
         */
        RCC->AHB1ENR |= RCC_AHB1ENR_GPIOFEN | RCC_AHB1ENR_GPIOHEN;
        (void)RCC->AHB1ENR;
        __DSB();
        GPIOF->MODER = (GPIOF->MODER & ~((3U << 4) | (3U << 6) | (3U << 8) | (3U << 22)))
                     | ((1U << 4) | (1U << 6) | (1U << 8) | (1U << 22));
        GPIOF->BSRR = (1U << 2) | (1U << 3) | (1U << 4) | (1U << 11);
        GPIOG->MODER = (GPIOG->MODER & ~(3U << 20)) | (1U << 20);
        GPIOG->BSRR = (1U << 10);
        GPIOH->MODER = (GPIOH->MODER & ~(3U << 10)) | (1U << 10);
        GPIOH->BSRR = (1U << 5);
    }
#endif

    rt_kprintf("[BOARD-INIT] Board initialization complete\n");

    /* Feed IWDG at end of board_init — covers RT-Thread scheduler startup
     * and transition into the main thread before ap_rtt_iwdg_init() takes over. */
    IWDG->KR = 0xAAAAU;
}

#if defined(BSP_USING_SPI) && defined(HAL_RTT_SPI_ATTACH_LIST)
static int _spi_device_board_init(void)
{
    _spi_device_init();
    return 0;
}
INIT_DEVICE_EXPORT(_spi_device_board_init);
#endif

/* RGB LED init moved to AP_HAL_RTT::GPIO::init() — runs after DCache
 * and all RT-Thread subsystems are fully up.  Early board-init MODER
 * writes are unreliable (STM32F767 DCache interaction). */

/*
 * Sensor power pin init — must run BEFORE SPI device attachment so that
 * sensors are powered when SPIDevice probes them during initialization.
 */
static int _sensor_power_init(void)
{
#ifdef HAL_GPIO_VDD_3V3_SENSORS_EN_PIN
    rt_pin_mode(HAL_GPIO_VDD_3V3_SENSORS_EN_PIN, PIN_MODE_OUTPUT);
    rt_pin_write(HAL_GPIO_VDD_3V3_SENSORS_EN_PIN, HAL_GPIO_VDD_3V3_SENSORS_EN_INIT);
    rt_kprintf("[PWR] VDD_3V3_SENSORS_EN enabled (pin=0x%x)\n",
               (unsigned)HAL_GPIO_VDD_3V3_SENSORS_EN_PIN);
#endif
#ifdef HAL_GPIO_HEATER_EN_PIN
    rt_pin_mode(HAL_GPIO_HEATER_EN_PIN, PIN_MODE_OUTPUT);
    rt_pin_write(HAL_GPIO_HEATER_EN_PIN, HAL_GPIO_HEATER_EN_INIT);
    rt_kprintf("[PWR] HEATER_EN forced %s (pin=0x%x)\n",
               HAL_GPIO_HEATER_EN_INIT ? "HIGH" : "LOW",
               (unsigned)HAL_GPIO_HEATER_EN_PIN);
#endif
    return 0;
}
INIT_PREV_EXPORT(_sensor_power_init);

static int rtt_run_cpp_ctors(void)
{
    __libc_init_array();
    return 0;
}
INIT_COMPONENT_EXPORT(rtt_run_cpp_ctors);

#ifdef BSP_USING_SDIO
#include <dfs_fs.h>
#include <sys/stat.h>
#include <errno.h>

/* SD card power pin — from hwdef.h (HAL_GPIO_SD_CARD_PWR_PIN) */
#ifdef HAL_GPIO_SD_CARD_PWR_PIN
#define SD_POWER_PIN    HAL_GPIO_SD_CARD_PWR_PIN
#else
#define SD_POWER_PIN    GET_PIN(G, 7)   /* fallback default */
#endif
#define SD_MOUNT_POINT  "/"

volatile int rtt_sd_mount_stage = 0;
volatile int rtt_sd_mount_result = -99;

static void _sd_try_mount_once(void)
{
    static const char *const dev_names[] = { "sd", "sd0" };
    rt_device_t sd_dev = RT_NULL;
    const char *dev_name = RT_NULL;
    for (size_t i = 0; i < sizeof(dev_names) / sizeof(dev_names[0]); i++) {
        sd_dev = rt_device_find(dev_names[i]);
        if (sd_dev != RT_NULL) {
            dev_name = dev_names[i];
            break;
        }
    }
    if (sd_dev == RT_NULL) return;

    rtt_sd_mount_stage = 3;
    int ret = dfs_mount(dev_name, SD_MOUNT_POINT, "elm", 0, 0);
    if (ret == 0) {
        rtt_sd_mount_stage = 5;
        mkdir("/APM", 0777);
        mkdir("/APM/LOGS", 0777);
        mkdir("/APM/TERRAIN", 0777);
        mkdir("/APM/STORAGE", 0777);
        mkdir("/APM/scripts", 0777);
        rtt_sd_mount_stage = 10;
        rtt_sd_mount_result = 0;
        rt_kprintf("[sd] mounted %s on %s ok\n", dev_name, SD_MOUNT_POINT);
    } else {
        rt_kprintf("[sd] mount %s -> %s failed ret=%d errno=%d\n",
                   dev_name, SD_MOUNT_POINT, ret, rt_get_errno());
    }
}

extern void ap_rtt_iwdg_kick(void);

static void _sd_mount_thread(void *arg)
{
    (void)arg;
    rtt_sd_mount_stage = 1;
    rt_pin_mode(SD_POWER_PIN, PIN_MODE_OUTPUT);
    rt_pin_write(SD_POWER_PIN, PIN_HIGH);
    rt_thread_mdelay(300);
    ap_rtt_iwdg_kick();

    rtt_sd_mount_stage = 2;
    for (int round = 0; round < 120; round++) {
        ap_rtt_iwdg_kick();
        if (rtt_sd_mount_result == 0) break;
        _sd_try_mount_once();
        if (rtt_sd_mount_result == 0) break;
        rt_thread_mdelay(500);
        ap_rtt_iwdg_kick();
    }
    if (rtt_sd_mount_result != 0) {
        rtt_sd_mount_stage = -4;
        rtt_sd_mount_result = -4;
        rt_kprintf("[sd] mount failed after retries (no card or FS error)\n");
    }
}

/*
 * SD mount: INIT_APP_EXPORT spawns background thread only — no sync power
 * delay or mount retries in rt_components_init (ArduPilot main() unblocked).
 */
static int sd_card_mount_init(void)
{
    rt_thread_t th = rt_thread_create("sdmnt", _sd_mount_thread,
                                      RT_NULL, 2048,
                                      RT_THREAD_PRIORITY_MAX - 2, 20);
    if (th) rt_thread_startup(th);
    return 0;
}
INIT_APP_EXPORT(sd_card_mount_init);
#endif

/* ----------------------------------------------------------------
 *  True CPU idle measurement via DWT cycle counter + idle hook.
 *  rtt_cpu_idle_pct is updated every second; read via GDB or MAVLink.
 * ---------------------------------------------------------------- */
volatile uint32_t rtt_cpu_idle_pct = 0;
volatile uint32_t rtt_cpu_idle_cycles = 0;

static volatile uint32_t _idle_cycles_acc = 0;
static volatile uint32_t _idle_last_cyc = 0;
static volatile uint32_t _measure_start_cyc = 0;

static void _idle_hook(void)
{
    /* Feed IWDG every idle cycle — safety net when SysTick handler
     * is temporarily starved (SPI burst with __disable_irq, etc.).
     * Redundant with SysTick feed but zero-cost when idle. */
    *(volatile uint32_t *)0x40003000UL = 0xAAAAU;

    /* USB EP0 needs frequent service during enumeration; main/setup often
     * busy-waits without calling usb_lld_poll_rtt(). Throttle idle polls. */
    static uint8_t usb_idle_div;
    if ((++usb_idle_div & 0x0F) == 0 && !usb_lld_is_configured_rtt()) {
        usb_lld_poll_rtt();
    }

    uint32_t now = DWT->CYCCNT;
    if (_idle_last_cyc != 0) {
        _idle_cycles_acc += (now - _idle_last_cyc);
    }
    _idle_last_cyc = now;
}

static void _cpu_measure_thread(void *arg)
{
    (void)arg;
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;

    while (1) {
        _idle_cycles_acc = 0;
        _idle_last_cyc = 0;
        _measure_start_cyc = DWT->CYCCNT;
        rt_thread_mdelay(1000);
        uint32_t total = DWT->CYCCNT - _measure_start_cyc;
        uint32_t idle = _idle_cycles_acc;
        _idle_last_cyc = 0;
        rtt_cpu_idle_cycles = idle;
        if (total > 0) {
            rtt_cpu_idle_pct = (uint32_t)((uint64_t)idle * 100 / total);
        }
    }
}

static int _cpu_idle_monitor_init(void)
{
    rt_thread_idle_sethook(_idle_hook);
    rt_thread_t th = rt_thread_create("cpumon", _cpu_measure_thread,
                                      RT_NULL, 1024,
                                      RT_THREAD_PRIORITY_MAX - 1, 20);
    if (th) rt_thread_startup(th);
    return 0;
}
INIT_APP_EXPORT(_cpu_idle_monitor_init);
