/*
 * RT-Thread board init for AP_HAL_RTT — GENERIC template.
 * All board-specific configuration comes from hwdef.h macros
 * generated by rtt_hwdef.py from hwdef.dat.
 *
 * GPIO power pins: HAL_GPIO_<LABEL>_PIN / HAL_GPIO_<LABEL>_INIT
 * SPI attach:      HAL_RTT_SPI_ATTACH_LIST
 * Flash origin:    FLASH_ORIGIN
 */
#include <rtthread.h>
#include "board.h"
#include "drv_gpio.h"

#ifdef BSP_USING_SPI
#include "drv_spi.h"
#endif

#include "hwdef.h"

/* SPI Low-Level DMA driver (STM32F7 only) */
#ifdef SOC_SERIES_STM32F7
#include "drv_spi_lld.h"
#endif

extern int rt_hw_pin_init(void);
extern int rt_hw_usart_init(void);
extern void __libc_init_array(void);
extern void rt_hw_systick_init(void);

#if defined(BSP_USING_SPI) && defined(HAL_RTT_SPI_ATTACH_LIST)
struct spi_attach_entry {
    const char *bus_name;
    const char *dev_name;
    rt_base_t cs_pin;
};

static const struct spi_attach_entry _spi_attach_table[] = {
    HAL_RTT_SPI_ATTACH_LIST
};

static void _spi_device_init(void)
{
    rt_kprintf("[SPI-INIT] Starting SPI device attachment\n");
    for (unsigned i = 0; i < sizeof(_spi_attach_table) / sizeof(_spi_attach_table[0]); i++) {
        rt_err_t ret = rt_hw_spi_device_attach(_spi_attach_table[i].bus_name,
                                _spi_attach_table[i].dev_name,
                                _spi_attach_table[i].cs_pin);
        rt_kprintf("[SPI-ATTACH] %s -> %s cs=0x%x ret=%d\n",
                   _spi_attach_table[i].bus_name,
                   _spi_attach_table[i].dev_name,
                   (unsigned)_spi_attach_table[i].cs_pin, (int)ret);
        /* RTT's rt_spi_bus_attach_device_cspin() only calls rt_pin_mode(OUTPUT)
         * but does NOT drive CS HIGH (inactive).  All CS pins default to LOW
         * (asserted), causing MISO bus contention when multiple devices share
         * the same SPI bus (e.g. 5 IMUs on SPI1).  Drive CS HIGH here. */
        if (ret == RT_EOK && _spi_attach_table[i].cs_pin != PIN_NONE) {
            rt_pin_write(_spi_attach_table[i].cs_pin, PIN_HIGH);
        }
    }
    rt_kprintf("[SPI-INIT] SPI device attachment complete\n");
}
#endif

static void _mpu_config(void)
{
    __DMB();
    MPU->CTRL = 0;

    /*
     * Region 0: All SRAM (DTCM + SRAM1 + SRAM2), base 0x20000000, 1MB
     * Normal, Write-Through No Write-Allocate, NON-Shareable, Full Access.
     * S=0 forces local exclusive monitor for ldrex/strex, avoiding
     * STM32F7 AXI bus global-monitor PRECISERR on SRAM exclusive access.
     */
    MPU->RNR  = 0;
    MPU->RBAR = 0x20000000U;
    MPU->RASR = (0U  << 28) |  /* XN=0 */
                (3U  << 24) |  /* AP=011 full access */
                (0U  << 19) |  /* TEX=000 */
                (0U  << 18) |  /* S=0 non-shareable */
                (1U  << 17) |  /* C=1 cacheable */
                (0U  << 16) |  /* B=0 not bufferable */
                (0U  <<  8) |  /* SRD=0 */
                (19U <<  1) |  /* SIZE=19 → 1MB */
                (1U  <<  0);   /* ENABLE */

    /*
     * Region 1: Peripheral space (0x40000000, 512MB)
     * Device, non-cacheable, Shareable, Full Access, XN
     */
    MPU->RNR  = 1;
    MPU->RBAR = 0x40000000U;
    MPU->RASR = (1U  << 28) |  /* XN=1 no exec */
                (3U  << 24) |  /* AP=011 full access */
                (0U  << 19) |  /* TEX=000 */
                (1U  << 18) |  /* S=1 shareable */
                (0U  << 17) |  /* C=0 not cacheable */
                (1U  << 16) |  /* B=1 bufferable */
                (0U  <<  8) |  /* SRD=0 */
                (28U <<  1) |  /* SIZE=28 → 512MB */
                (1U  <<  0);   /* ENABLE */

    /*
     * Region 2: SDIO DMA buffer (cache_buf in .sram1_bss) — non-cacheable.
     * 16KB at 0x20020000, but only sub-regions 3-5 enabled (0x20021800–0x20022FFF)
     * via SRD mask. Higher region number overrides Region 0 for this range.
     */
    MPU->RNR  = 2;
    MPU->RBAR = 0x20020000U;
    MPU->RASR = (0U  << 28) |  /* XN=0 */
                (3U  << 24) |  /* AP=011 full access */
                (1U  << 19) |  /* TEX=001 normal non-cacheable */
                (0U  << 18) |  /* S=0 */
                (0U  << 17) |  /* C=0 */
                (0U  << 16) |  /* B=0 */
                (0xC7U << 8) | /* SRD=11000111: disable sub 0,1,2,6,7; enable 3,4,5 */
                (13U <<  1) |  /* SIZE=13 → 16KB */
                (1U  <<  0);   /* ENABLE */

    MPU->CTRL = MPU_CTRL_PRIVDEFENA_Msk | MPU_CTRL_ENABLE_Msk;
    __DSB();
    __ISB();
}

static void _fpu_context_init(void)
{
#if defined (__VFP_FP__) && !defined(__SOFTFP__)
    /*
     * Lua scripting mixes hard-float code with frequent RT-Thread context
     * switches. Disable lazy stacking so exception entry always materializes
     * the low FPU frame on the owning thread stack instead of deferring via
     * FPCAR/LSPACT, which has been triggering INVSTATE during mixed FPU/non-FPU
     * thread switches on CUAV V5 bring-up.
     */
    FPU->FPCCR |= FPU_FPCCR_ASPEN_Msk;
    FPU->FPCCR &= ~FPU_FPCCR_LSPEN_Msk;
    __DSB();
    __ISB();
#endif
}

/*
 * SPI LLD contexts for STM32F7 DMA-backed buses.
 * Registered before rt_components_board_init() so that rt_hw_spi_init()
 * (INIT_BOARD_EXPORT) finds them during rt_hw_spi_bus_init().
 */
#ifdef SOC_SERIES_STM32F7
#if defined(BSP_USING_SPI1) && defined(BSP_SPI1_TX_USING_DMA) && defined(BSP_SPI1_RX_USING_DMA)
static spi_lld_bus_t s_spi1_lld = {
    .spi     = SPI1,
    .dma_rx  = SPI1_RX_DMA_INSTANCE,
    .dma_tx  = SPI1_TX_DMA_INSTANCE,
    .ch_rx   = SPI1_RX_DMA_CHANNEL,
    .ch_tx   = SPI1_TX_DMA_CHANNEL,
    .irq_rx  = SPI1_RX_DMA_IRQ,
    .irq_tx  = SPI1_TX_DMA_IRQ,
};
#endif

#if defined(BSP_USING_SPI4) && defined(BSP_SPI4_TX_USING_DMA) && defined(BSP_SPI4_RX_USING_DMA)
static spi_lld_bus_t s_spi4_lld = {
    .spi     = SPI4,
    .dma_rx  = SPI4_RX_DMA_INSTANCE,
    .dma_tx  = SPI4_TX_DMA_INSTANCE,
    .ch_rx   = SPI4_RX_DMA_CHANNEL,
    .ch_tx   = SPI4_TX_DMA_CHANNEL,
    .irq_rx  = SPI4_RX_DMA_IRQ,
    .irq_tx  = SPI4_TX_DMA_IRQ,
};
#endif

static void _spi_lld_board_init(void)
{
    /*
     * SPI1 LLD DMA disabled: manual OpenOCD polling returns correct
     * WHO_AM_I (0x98) but DMA returns 0xFF.  Root cause suspected:
     * DMA2 Stream2/Channel3 (SPI1_RX) reads stale FIFO data or has a
     * cache/buffer-address issue specific to the SPI1 DMA path.
     * SPI4 DMA (barometer) works fine.  Until the DMA root cause is
     * found, SPI1 falls back to the RTT framework's HAL polling path
     * which works correctly at the cost of slightly higher CPU usage.
     */
#if 0  /* was: defined(BSP_USING_SPI1) && ... */
    spi_lld_register(&s_spi1_lld);
    spi_lld_bus_init(&s_spi1_lld);
    HAL_NVIC_SetPriority(SPI1_RX_DMA_IRQ, 5, 0);
    HAL_NVIC_EnableIRQ(SPI1_RX_DMA_IRQ);
    HAL_NVIC_SetPriority(SPI1_TX_DMA_IRQ, 5, 1);
    HAL_NVIC_EnableIRQ(SPI1_TX_DMA_IRQ);
#endif
#if defined(BSP_USING_SPI4) && defined(BSP_SPI4_TX_USING_DMA) && defined(BSP_SPI4_RX_USING_DMA)
    spi_lld_register(&s_spi4_lld);
    spi_lld_bus_init(&s_spi4_lld);
    /*
     * Do NOT enable SPI4 DMA NVIC here.
     * spi_bus_obj[x].lld is only attached later in rt_hw_spi_init()
     * during rt_components_board_init(). Enabling the IRQs before that
     * allows stale DMA interrupts to hit the HAL fallback path with an
     * uninitialized handle/context, which can HardFault early in boot.
     *
     * Leave the streams quiesced here; enable NVIC only after the SPI
     * bus object has attached the LLD context.
     */
#endif
}
#endif /* SOC_SERIES_STM32F7 */

void rt_hw_board_init(void)
{
    rt_kprintf("[BOARD-INIT] Starting board initialization\n");
#ifdef FLASH_ORIGIN
    SCB->VTOR = FLASH_ORIGIN;
#else
    SCB->VTOR = 0x08008000U;
#endif

    _mpu_config();
    _fpu_context_init();
    SCB_EnableICache();
    // SCB_EnableDCache();  // Disabled: USB DWC2 DMA coherency issues on STM32F7

    /* Minimal HAL_Init() equivalent — direct register operations */
    FLASH->ACR |= FLASH_ACR_ARTEN | FLASH_ACR_PRFTEN;
    NVIC_SetPriorityGrouping(3U);  /* PRIGROUP=3 → 4-bit preemption (same as HAL NVIC_PRIORITYGROUP_4) */

    SystemClock_Config();
    rt_hw_systick_init();
    rt_hw_pin_init();
    rt_hw_usart_init();

    /* GPIO power pins moved to _sensor_power_init (INIT_PREV_EXPORT) —
     * DCache interference causes MODER writes at this early stage to be
     * lost when HAL_SPI_MspInit later does read-modify-write on the same
     * GPIO port (e.g. SPI4 HAL_GPIO_Init on GPIOE clobbers PE3). */

#ifdef RT_USING_HEAP
    rt_system_heap_init(HEAP_BEGIN, HEAP_END);
#endif

#ifdef RT_USING_CONSOLE
    rt_console_set_device(RT_CONSOLE_DEVICE_NAME);
#endif

    /* Register SPI LLD contexts before rt_components_board_init() so that
     * rt_hw_spi_init() (INIT_BOARD_EXPORT) finds them. */
#ifdef SOC_SERIES_STM32F7
#if (defined(BSP_USING_SPI1) && defined(BSP_SPI1_TX_USING_DMA) && defined(BSP_SPI1_RX_USING_DMA)) || \
    (defined(BSP_USING_SPI4) && defined(BSP_SPI4_TX_USING_DMA) && defined(BSP_SPI4_RX_USING_DMA))
    _spi_lld_board_init();
#endif
#endif

    rt_kprintf("[BOARD-INIT] Calling rt_components_board_init()\n");
#ifdef RT_USING_COMPONENTS_INIT
    rt_components_board_init();
#endif

    /* Workaround: SPI1 MOSI (PB5) MODER gets reset to INPUT by a subsequent
     * HAL_GPIO_Init on the same GPIO port (GPIOB). The STM32F7 HAL performs
     * read-modify-write on MODER/AFR and the write may be lost if another
     * caller touches the same register concurrently or in a later init step.
     * Force PB5 back to AF mode here, and ensure PG9 (MISO) is also AF,
     * after all board init is done. */
#ifdef BSP_USING_SPI1
    {
        volatile uint32_t *moder_b = (volatile uint32_t *)0x40020400; /* GPIOB */
        uint32_t m = *moder_b;
        m &= ~(3U << 10);  /* clear PB5 MODER bits */
        m |= (2U << 10);   /* set AF mode */
        *moder_b = m;
        /* PG9 MISO — force AF mode */
        volatile uint32_t *moder_g = (volatile uint32_t *)0x40021800; /* GPIOG */
        m = *moder_g;
        m &= ~(3U << 18);  /* clear PG9 MODER bits */
        m |= (2U << 18);   /* set AF mode */
        *moder_g = m;
        volatile uint32_t *afr_g = (volatile uint32_t *)(0x40021800 + 0x24); /* GPIOG AFR[1] */
        m = *afr_g;
        m &= ~(0xFU << 4); /* clear PG9 AF bits */
        m |= (5U << 4);    /* AF5 */
        *afr_g = m;
    }
    /* Force SPI1 clock on — HAL_SPI_MspInit may not be reached if
     * rt_hw_spi_init() fails or SPI device registration is incomplete.
     * Without SPI1 clock, all IMU sensor reads return 0xFFFF. */
    RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;
#endif
#ifdef BSP_USING_SPI4
    /* SPI4 GPIO — CUAV V5: PE12(SCK), PE13(MISO), PE14(MOSI), PF10(CS).
     * Both the CubeMX HAL_SPI_MspInit and AP_HAL_RTT drv_spi_ll init
     * go through this register-level IO, so we force-correct it here
     * regardless of which init path is taken. */
    RCC->APB2ENR |= RCC_APB2ENR_SPI4EN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOFEN;
    (void)RCC->AHB1ENR;
    /* PE12=SCK(AF5): MODER=AF, AFR[1]=AF5 */
    GPIOE->MODER = (GPIOE->MODER & ~(3U << 24)) | (2U << 24);
    GPIOE->AFR[1] = (GPIOE->AFR[1] & ~(0xFU << 16)) | (5U << 16);
    /* PE13=MISO(AF5) */
    GPIOE->MODER = (GPIOE->MODER & ~(3U << 26)) | (2U << 26);
    GPIOE->AFR[1] = (GPIOE->AFR[1] & ~(0xFU << 20)) | (5U << 20);
    /* PE14=MOSI(AF5) */
    GPIOE->MODER = (GPIOE->MODER & ~(3U << 28)) | (2U << 28);
    GPIOE->AFR[1] = (GPIOE->AFR[1] & ~(0xFU << 24)) | (5U << 24);
    /* MS5611 CS (PF10): OUTPUT HIGH */
    GPIOF->MODER = (GPIOF->MODER & ~(3U << 20)) | (1U << 20);
    GPIOF->BSRR = (1U << 10);
#endif

    rt_kprintf("[BOARD-INIT] Board initialization complete\n");
}

#if defined(BSP_USING_SPI) && defined(HAL_RTT_SPI_ATTACH_LIST)
static int _spi_device_board_init(void)
{
    _spi_device_init();
    return 0;
}
INIT_DEVICE_EXPORT(_spi_device_board_init);
#endif

/* RGB LED init moved to AP_HAL_RTT::GPIO::init() — runs after DCache
 * and all RT-Thread subsystems are fully up.  Early board-init MODER
 * writes are unreliable (STM32F767 DCache interaction). */

/*
 * Sensor power pin init — must run BEFORE SPI device attachment so that
 * sensors are powered when SPIDevice probes them during initialization.
 */
static int _sensor_power_init(void)
{
#ifdef HAL_GPIO_VDD_3V3_SENSORS_EN_PIN
    rt_pin_mode(HAL_GPIO_VDD_3V3_SENSORS_EN_PIN, PIN_MODE_OUTPUT);
    rt_pin_write(HAL_GPIO_VDD_3V3_SENSORS_EN_PIN, HAL_GPIO_VDD_3V3_SENSORS_EN_INIT);
    rt_kprintf("[PWR] VDD_3V3_SENSORS_EN enabled (pin=0x%x)\n",
               (unsigned)HAL_GPIO_VDD_3V3_SENSORS_EN_PIN);
#endif
#ifdef HAL_GPIO_HEATER_EN_PIN
    rt_pin_mode(HAL_GPIO_HEATER_EN_PIN, PIN_MODE_OUTPUT);
    rt_pin_write(HAL_GPIO_HEATER_EN_PIN, HAL_GPIO_HEATER_EN_INIT);
    rt_kprintf("[PWR] HEATER_EN forced %s (pin=0x%x)\n",
               HAL_GPIO_HEATER_EN_INIT ? "HIGH" : "LOW",
               (unsigned)HAL_GPIO_HEATER_EN_PIN);
#endif
    return 0;
}
INIT_PREV_EXPORT(_sensor_power_init);

static int rtt_run_cpp_ctors(void)
{
    __libc_init_array();
    return 0;
}
INIT_COMPONENT_EXPORT(rtt_run_cpp_ctors);

/* Always define for AP_Logger_File.cpp */
volatile int rtt_sd_mount_stage = 0;
volatile int rtt_sd_mount_result = -99;

#ifdef BSP_USING_SDIO
#include <dfs_fs.h>
#include <sys/stat.h>
#include <errno.h>

/* SD card power pin — from hwdef.h (HAL_GPIO_SD_CARD_PWR_PIN) */
#ifdef HAL_GPIO_SD_CARD_PWR_PIN
#define SD_POWER_PIN    HAL_GPIO_SD_CARD_PWR_PIN
#else
#define SD_POWER_PIN    GET_PIN(G, 7)   /* fallback default */
#endif
#define SD_MOUNT_POINT  "/"

static void _sd_try_mount_once(void)
{
    static const char *const dev_names[] = { "sd", "sd0" };
    rt_device_t sd_dev = RT_NULL;
    const char *dev_name = RT_NULL;
    for (size_t i = 0; i < sizeof(dev_names) / sizeof(dev_names[0]); i++) {
        sd_dev = rt_device_find(dev_names[i]);
        if (sd_dev != RT_NULL) {
            dev_name = dev_names[i];
            break;
        }
    }
    if (sd_dev == RT_NULL) return;

    rtt_sd_mount_stage = 3;
    int ret = dfs_mount(dev_name, SD_MOUNT_POINT, "elm", 0, 0);
    if (ret == 0) {
        rtt_sd_mount_stage = 5;
        mkdir("/APM", 0777);
        mkdir("/APM/LOGS", 0777);
        mkdir("/APM/TERRAIN", 0777);
        mkdir("/APM/STORAGE", 0777);
        mkdir("/APM/scripts", 0777);
        rtt_sd_mount_stage = 10;
        rtt_sd_mount_result = 0;
        rt_kprintf("[sd] mounted %s on %s ok\n", dev_name, SD_MOUNT_POINT);
    } else {
        rt_kprintf("[sd] mount %s -> %s failed ret=%d errno=%d\n",
                   dev_name, SD_MOUNT_POINT, ret, rt_get_errno());
    }
}

static void _sd_mount_thread(void *arg)
{
    (void)arg;
    for (int round = 0; round < 120; round++) {
        if (rtt_sd_mount_result == 0) break;
        _sd_try_mount_once();
        if (rtt_sd_mount_result == 0) break;
        rt_thread_mdelay(500);
    }
    if (rtt_sd_mount_result != 0) {
        rtt_sd_mount_stage = -4;
        rtt_sd_mount_result = -4;
        rt_kprintf("[sd] mount failed after retries (no card or FS error)\n");
    }
}

/*
 * SD mount: quick try in INIT_ENV_EXPORT, then spawn background thread for
 * retries so main() (ArduPilot) is not blocked for 60s when no card present.
 */
static int sd_card_mount_sync(void)
{
    rtt_sd_mount_stage = 1;
    rt_pin_mode(SD_POWER_PIN, PIN_MODE_OUTPUT);
    rt_pin_write(SD_POWER_PIN, PIN_HIGH);
    rt_thread_mdelay(300);

    rtt_sd_mount_stage = 2;
    _sd_try_mount_once();
    if (rtt_sd_mount_result == 0) return 0;

    /* Card not ready yet — spawn background retry thread */
    rt_thread_t th = rt_thread_create("sdmnt", _sd_mount_thread,
                                      RT_NULL, 2048,
                                      RT_THREAD_PRIORITY_MAX - 2, 20);
    if (th) rt_thread_startup(th);
    return 0;
}
INIT_ENV_EXPORT(sd_card_mount_sync);
#endif

/* ----------------------------------------------------------------
 *  Internal Flash block device for DFS elmfat (logging without SD).
 *  Uses sector 11 (256KB) — sector 10 is HAL_Storage parameters.
 * ---------------------------------------------------------------- */
extern int rt_hw_flash_blkdev_init(void);

#define FLASH_BLKDEV_MOUNT_POINT  "/logs"
#define FLASH_BLKDEV_DEV          "flash0"

static int flash_blkdev_mount(void)
{
    if (rt_hw_flash_blkdev_init() != RT_EOK) return -1;

    /* Try mounting first; if no filesystem, format then mount */
    if (dfs_mount(FLASH_BLKDEV_DEV, FLASH_BLKDEV_MOUNT_POINT, "elm", 0, 0) == 0) {
        rt_kprintf("[flash0] mounted on %s\n", FLASH_BLKDEV_MOUNT_POINT);
        return 0;
    }

    rt_kprintf("[flash0] no filesystem, formatting...\n");
    int rc = dfs_mkfs("elm", FLASH_BLKDEV_DEV);
    if (rc != 0) {
        rt_kprintf("[flash0] mkfs failed: %d\n", rc);
        return -2;
    }

    rc = dfs_mount(FLASH_BLKDEV_DEV, FLASH_BLKDEV_MOUNT_POINT, "elm", 0, 0);
    if (rc != 0) {
        rt_kprintf("[flash0] mount after mkfs failed: %d\n", rc);
        return -3;
    }

    mkdir(FLASH_BLKDEV_MOUNT_POINT, 0777);
    rt_kprintf("[flash0] formatted and mounted on %s\n", FLASH_BLKDEV_MOUNT_POINT);
    return 0;
}
INIT_ENV_EXPORT(flash_blkdev_mount);

/* ----------------------------------------------------------------
 *  True CPU idle measurement via DWT cycle counter + idle hook.
 *  rtt_cpu_idle_pct is updated every second; read via GDB or MAVLink.
 * ---------------------------------------------------------------- */
volatile uint32_t rtt_cpu_idle_pct = 0;
volatile uint32_t rtt_cpu_idle_cycles = 0;

static volatile uint32_t _idle_cycles_acc = 0;
static volatile uint32_t _idle_last_cyc = 0;
static volatile uint32_t _measure_start_cyc = 0;

static void _idle_hook(void)
{
    uint32_t now = DWT->CYCCNT;
    if (_idle_last_cyc != 0) {
        _idle_cycles_acc += (now - _idle_last_cyc);
    }
    _idle_last_cyc = now;
}

static void _cpu_measure_thread(void *arg)
{
    (void)arg;
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;

    while (1) {
        _idle_cycles_acc = 0;
        _idle_last_cyc = 0;
        _measure_start_cyc = DWT->CYCCNT;
        rt_thread_mdelay(1000);
        uint32_t total = DWT->CYCCNT - _measure_start_cyc;
        uint32_t idle = _idle_cycles_acc;
        _idle_last_cyc = 0;
        rtt_cpu_idle_cycles = idle;
        if (total > 0) {
            rtt_cpu_idle_pct = (uint32_t)((uint64_t)idle * 100 / total);
        }
    }
}

static int _cpu_idle_monitor_init(void)
{
    rt_thread_idle_sethook(_idle_hook);
    rt_thread_t th = rt_thread_create("cpumon", _cpu_measure_thread,
                                      RT_NULL, 1024,
                                      RT_THREAD_PRIORITY_MAX - 1, 20);
    if (th) rt_thread_startup(th);
    return 0;
}
INIT_APP_EXPORT(_cpu_idle_monitor_init);
