import os
from building import *

cwd = GetCurrentDir()
src = []

if os.path.isfile(os.path.join(cwd, 'phy_reset.c')):
    src += ['phy_reset.c']

group = DefineGroup('Ports', src, depend=[''], CPPPATH=[cwd])

items = os.listdir(cwd)
for item in items:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

objs = group
Return('objs')
