import os
from building import *

cwd = GetCurrentDir()

# Test source
src = Glob('*.c')

# Include common test framework from parent directory
common_dir = os.path.normpath(os.path.join(cwd, '..', '..', '_common'))

# Common test framework sources
src += Glob(os.path.join(common_dir, 'test_runner.c'))
src += Glob(os.path.join(common_dir, 'test_stubs.c'))

CPPPATH = [cwd, common_dir]

group = DefineGroup('test_L2_gpio', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
