/*
 * AP_HAL_RTT — GPIO driver implementation
 * Pure CMSIS register access for all GPIO operations (MODER, OTYPER, OSPEEDR,
 * PUPDR, IDR, ODR, BSSR) and EXTI interrupt configuration (SYSCFG EXTICR,
 * EXTI IMR/FTSR/RTSR/PR, NVIC).
 *
 * Pin numbers: port_idx * 16 + pin_num  (port_idx: A=0, B=1, ..., I=8).
 * This matches the GET_PIN(port,num) convention and the _VALUE macros
 * generated by rtt_hwdef.py.
 *
 * Reference: ChibiOS GPIOv3/hal_pal_lld.c and stm32_gpio.h
 */

#include "GPIO.h"
#include <AP_HAL/AP_HAL.h>
#include <stm32f7xx.h>
#include <cstdio>
#include <hal_usb_lld_rtt.h>

/* Keep RT-Thread kernel include only for rt_thread_mdelay() in wait_pin() */
#include <rtthread.h>

using namespace RTT;

/* ---------------------------------------------------------------------------
 * CMSIS register-level GPIO helpers
 * ------------------------------------------------------------------------- */

/* GPIO port base: A=0x40020000, B=0x40020400, ... step 0x400 */
#define _GPIO_REG(port, offset) \
    (*(volatile uint32_t *)(GPIOA_BASE + ((uint32_t)(port) << 10U) + (offset)))

/* Get GPIO_TypeDef pointer from port index */
static inline GPIO_TypeDef *_gpio_port(uint8_t port)
{
    return (GPIO_TypeDef *)(GPIOA_BASE + ((uint32_t)port << 10U));
}

/* Enable GPIO port clock via RCC AHB1ENR.  Safe to call multiple times. */
static inline void _gpio_clk_enable(uint8_t port)
{
    if (port <= 8) {
        RCC->AHB1ENR |= (1U << port);
        (void)RCC->AHB1ENR; /* ensure write completes */
    }
}

/* Extract port index and pin number from composite pin value */
#define _PIN_PORT(pin)  ((uint8_t)((pin) >> 4))
#define _PIN_BIT(pin)   ((uint8_t)((pin) & 0x0F))
#define _PIN_MASK(pin)  (1UL << _PIN_BIT(pin))

/* ---------------------------------------------------------------------------
 * DigitalSource
 * ------------------------------------------------------------------------- */

DigitalSource::DigitalSource(uint16_t pin) : _pin(pin) {}

void DigitalSource::mode(uint8_t output)
{
    uint8_t port = _PIN_PORT(_pin);
    uint8_t bit  = _PIN_BIT(_pin);
    GPIO_TypeDef *gpio = _gpio_port(port);

    _gpio_clk_enable(port);

    if (output == HAL_GPIO_INPUT) {
        /* INPUT mode */
        gpio->MODER &= ~(3UL << (bit * 2));
        gpio->PUPDR &= ~(3UL << (bit * 2));
        __DSB();
    } else {
        /* Check if open-drain is already set (retain existing OTYPER) */
        if ((gpio->OTYPER >> bit) & 1U) {
            /* Open-drain output */
            gpio->MODER = (gpio->MODER & ~(3UL << (bit * 2))) | (1UL << (bit * 2));
            gpio->OSPEEDR = (gpio->OSPEEDR & ~(3UL << (bit * 2))) | (2UL << (bit * 2));
            gpio->PUPDR &= ~(3UL << (bit * 2));
            __DSB();
        } else {
            /* Push-pull output */
            gpio->MODER = (gpio->MODER & ~(3UL << (bit * 2))) | (1UL << (bit * 2));
            gpio->OTYPER &= ~(1UL << bit);
            gpio->OSPEEDR = (gpio->OSPEEDR & ~(3UL << (bit * 2))) | (2UL << (bit * 2));
            gpio->PUPDR &= ~(3UL << (bit * 2));
            __DSB();
        }
    }
}

uint8_t DigitalSource::read()
{
    uint8_t port = _PIN_PORT(_pin);
    uint8_t bit  = _PIN_BIT(_pin);
    return (_gpio_port(port)->IDR >> bit) & 1U;
}

void DigitalSource::write(uint8_t value)
{
    uint8_t port = _PIN_PORT(_pin);
    GPIO_TypeDef *gpio = _gpio_port(port);
    if (value) {
        gpio->BSRR = _PIN_MASK(_pin);          /* set output → HIGH */
    } else {
        gpio->BSRR = _PIN_MASK(_pin) << 16U;   /* reset output → LOW */
    }
}

void DigitalSource::toggle()
{
    _gpio_port(_PIN_PORT(_pin))->ODR ^= _PIN_MASK(_pin);
}

/* ---------------------------------------------------------------------------
 * GPIO
 * ------------------------------------------------------------------------- */

GPIO::IRQState GPIO::_irq_state[RTT_GPIO_MAX_IRQ] = {};

void GPIO::init()
{
    /*
     * Power-on sensor rails and other output GPIOs with INIT=1 from hwdef.h.
     * This MUST run before any SPI/I2C sensor communication.
     *
     * Uses the _VALUE macros (precomputed integer pin numbers) available
     * from hwdef.h, encoded as port*16 + bit.
     */
    struct gpio_init_entry {
        uint8_t pin;
        uint8_t init_value;  /* 0=LOW, 1=HIGH */
    };
    static const gpio_init_entry init_list[] = {
#ifdef HAL_GPIO_VDD_3V3_SENSORS_EN_VALUE
        { HAL_GPIO_VDD_3V3_SENSORS_EN_VALUE,
#ifdef HAL_GPIO_VDD_3V3_SENSORS_EN_INIT
          HAL_GPIO_VDD_3V3_SENSORS_EN_INIT
#else
          1
#endif
        },
#endif
#ifdef HAL_GPIO_VDD_5V_RC_EN_VALUE
        { HAL_GPIO_VDD_5V_RC_EN_VALUE,
#ifdef HAL_GPIO_VDD_5V_RC_EN_INIT
          HAL_GPIO_VDD_5V_RC_EN_INIT
#else
          1
#endif
        },
#endif
#ifdef HAL_GPIO_VDD_3V3_SD_CARD_EN_VALUE
        { HAL_GPIO_VDD_3V3_SD_CARD_EN_VALUE,
#ifdef HAL_GPIO_VDD_3V3_SD_CARD_EN_INIT
          HAL_GPIO_VDD_3V3_SD_CARD_EN_INIT
#else
          1
#endif
        },
#endif
#ifdef HAL_GPIO_VDD_5V_WIFI_EN_VALUE
        { HAL_GPIO_VDD_5V_WIFI_EN_VALUE,
#ifdef HAL_GPIO_VDD_5V_WIFI_EN_INIT
          HAL_GPIO_VDD_5V_WIFI_EN_INIT
#else
          1
#endif
        },
#endif
#ifdef HAL_GPIO_SPEKTRUM_PWR_VALUE
        { HAL_GPIO_SPEKTRUM_PWR_VALUE,
#ifdef HAL_GPIO_SPEKTRUM_PWR_INIT
          HAL_GPIO_SPEKTRUM_PWR_INIT
#else
          1
#endif
        },
#endif
#ifdef HAL_GPIO_nVDD_5V_HIPOWER_EN_VALUE
        { HAL_GPIO_nVDD_5V_HIPOWER_EN_VALUE,
#ifdef HAL_GPIO_nVDD_5V_HIPOWER_EN_INIT
          HAL_GPIO_nVDD_5V_HIPOWER_EN_INIT
#else
          1
#endif
        },
#endif
#ifdef HAL_GPIO_nVDD_5V_PERIPH_EN_VALUE
        { HAL_GPIO_nVDD_5V_PERIPH_EN_VALUE,
#ifdef HAL_GPIO_nVDD_5V_PERIPH_EN_INIT
          HAL_GPIO_nVDD_5V_PERIPH_EN_INIT
#else
          1
#endif
        },
#endif
#ifdef HAL_GPIO_nSPI5_RESET_EXTERNAL1_VALUE
        { HAL_GPIO_nSPI5_RESET_EXTERNAL1_VALUE,
#ifdef HAL_GPIO_nSPI5_RESET_EXTERNAL1_INIT
          HAL_GPIO_nSPI5_RESET_EXTERNAL1_INIT
#else
          1
#endif
        },
#endif
    };

    for (const auto &e : init_list) {
        uint8_t port = _PIN_PORT(e.pin);
        uint8_t bit  = _PIN_BIT(e.pin);
        GPIO_TypeDef *gpio = _gpio_port(port);
        _gpio_clk_enable(port);
        /* Configure as push-pull output */
        gpio->MODER = (gpio->MODER & ~(3UL << (bit * 2))) | (1UL << (bit * 2));
        gpio->OTYPER &= ~(1UL << bit);
        gpio->OSPEEDR = (gpio->OSPEEDR & ~(3UL << (bit * 2))) | (2UL << (bit * 2));
        gpio->PUPDR &= ~(3UL << (bit * 2));
        __DSB();
        /* Set initial value via BSRR */
        if (e.init_value) {
            gpio->BSRR = _PIN_MASK(e.pin);           /* set → HIGH */
        } else {
            gpio->BSRR = _PIN_MASK(e.pin) << 16U;    /* reset → LOW */
        }
    }

    /* Lazy MODER init for RGB LED (PH10/11/12) is done in write() on first use,
     * because TIM12 HAL_GPIO_Init (stm32f7xx_hal_msp.c) clobbers GPIOH->MODER
     * after this point. */
}

void GPIO::pinMode(uint8_t pin, uint8_t output)
{
    if (pin >= 176) return;
    uint8_t port = _PIN_PORT(pin);
    uint8_t bit  = _PIN_BIT(pin);
    GPIO_TypeDef *gpio = _gpio_port(port);
    _gpio_clk_enable(port);

    if (output == HAL_GPIO_INPUT) {
        /* Input mode, no pull */
        gpio->MODER &= ~(3UL << (bit * 2));
        gpio->PUPDR &= ~(3UL << (bit * 2));
        __DSB();
    } else {
        /*
         * Retain OPENDRAIN if already set (mirrors ChibiOS behavior on
         * STM32F7/H7/F4/G4/L4).  Read OTYPER directly to check.
         */
        if ((gpio->OTYPER >> bit) & 1U) {
            /* Open-drain output */
            gpio->MODER = (gpio->MODER & ~(3UL << (bit * 2))) | (1UL << (bit * 2));
            gpio->OSPEEDR = (gpio->OSPEEDR & ~(3UL << (bit * 2))) | (2UL << (bit * 2));
            gpio->PUPDR &= ~(3UL << (bit * 2));
            __DSB();
        } else {
            /* Push-pull output */
            gpio->MODER = (gpio->MODER & ~(3UL << (bit * 2))) | (1UL << (bit * 2));
            gpio->OTYPER &= ~(1UL << bit);
            gpio->OSPEEDR = (gpio->OSPEEDR & ~(3UL << (bit * 2))) | (2UL << (bit * 2));
            gpio->PUPDR &= ~(3UL << (bit * 2));
            __DSB();
        }
    }
}

void GPIO::pinMode(uint8_t pin, uint8_t output, uint8_t alt)
{
    (void)alt;
    pinMode(pin, output);
}

uint8_t GPIO::read(uint8_t pin)
{
    if (pin >= 176) return 0;
    uint8_t port = _PIN_PORT(pin);
    uint8_t bit  = _PIN_BIT(pin);
    return (_gpio_port(port)->IDR >> bit) & 1U;
}

void GPIO::write(uint8_t pin, uint8_t value)
{
    if (pin >= 176) return;

    _gpio_clk_enable(_PIN_PORT(pin));

#if AP_NOTIFY_GPIO_LED_RGB_ENABLED && defined(AP_NOTIFY_GPIO_LED_RGB_RED_PIN)
    /* RGB LED pins on CUAV V5: PH10(R) / PH11(G) / PH12(B), active-low.
     * ChibiOS configures these as OPENDRAIN. The LED turns ON when pin is
     * LOW (open-drain sinks current). Write BSRR directly.
     * BSRR: bits[15:0] set ODR (pin HIGH), bits[31:16] reset ODR (pin LOW).
     */
    if (pin == AP_NOTIFY_GPIO_LED_RGB_RED_PIN ||
        pin == AP_NOTIFY_GPIO_LED_RGB_GREEN_PIN ||
        pin == AP_NOTIFY_GPIO_LED_RGB_BLUE_PIN) {
        static bool led_moder_done = false;
        if (!led_moder_done) {
            RCC->AHB1ENR |= RCC_AHB1ENR_GPIOHEN;
            /* Set PH10/11/12 to OUTPUT (MODER bits 21:20, 23:22, 25:24 = 01) */
            GPIOH->MODER = (GPIOH->MODER & ~(0x3FUL << 20)) | (0x15UL << 20);
            __DSB();
            /* Set PH10/11/12 to open-drain (OTYPER bits 10,11,12 = 1) */
            GPIOH->OTYPER |= (0x7UL << 10);
            __DSB();
            /* Set ODR HIGH (LED off — open-drain HIGH = floating) */
            GPIOH->BSRR = (0x7UL << 10);
            led_moder_done = true;
        }
        uint8_t bit = _PIN_BIT(pin);
        if (value) {
            GPIOH->BSRR = 1UL << bit;        /* set ODR → pin HIGH → LED off */
        } else {
            GPIOH->BSRR = 1UL << (bit + 16); /* reset ODR → pin LOW → LED on */
        }
        return;
    }
#endif

    /*
     * ChibiOS semantics: writing to an input-configured pin controls
     * pull-up/pull-down resistors.  Read MODER to check current mode.
     */
    uint8_t port = _PIN_PORT(pin);
    uint8_t bit  = _PIN_BIT(pin);
    GPIO_TypeDef *gpio = _gpio_port(port);
    uint32_t mode = (gpio->MODER >> (bit * 2)) & 0x03U;

    if (mode == 0) {
        /* Pin is in INPUT mode — set pull-up/pull-down via PUPDR */
        uint32_t pup = value ? 1UL : 2UL; /* 1=PullUp, 2=PullDown */
        gpio->PUPDR = (gpio->PUPDR & ~(3UL << (bit * 2))) | (pup << (bit * 2));
        __DSB();
        return;
    }

    /* Output mode — write via BSRR */
    if (value) {
        gpio->BSRR = _PIN_MASK(pin);          /* set → HIGH */
    } else {
        gpio->BSRR = _PIN_MASK(pin) << 16U;   /* reset → LOW */
    }
}

void GPIO::toggle(uint8_t pin)
{
    /* Atomic toggle via direct ODR XOR (same as STM32 HAL_GPIO_TogglePin). */
    if (pin >= 176) return;
    uint8_t port = _PIN_PORT(pin);
    _gpio_port(port)->ODR ^= _PIN_MASK(pin);
}

AP_HAL::DigitalSource* GPIO::channel(uint16_t n)
{
    return NEW_NOTHROW DigitalSource(n);
}

/* CherryUSB removed — use RTT DWC2 LLD instead */

bool GPIO::usb_connected()
{
    return usb_lld_is_configured_rtt();
}

/* ---------------------------------------------------------------------------
 * Interrupt support — direct EXTI + SYSCFG + NVIC configuration
 * ---------------------------------------------------------------------------
 *
 * On STM32F7, EXTI lines 0–15 correspond to GPIO pin numbers 0–15 within a
 * port.  Each EXTI line must be routed to one specific GPIO port via the
 * SYSCFG EXTICR registers.  We support up to RTT_GPIO_MAX_IRQ (8) concurrent
 * pin interrupts.
 *
 * IRQ groups (NVIC):
 *   EXTI0_IRQn  (IRQ 6)   — line 0
 *   EXTI1_IRQn  (IRQ 7)   — line 1
 *   EXTI2_IRQn  (IRQ 8)   — line 2
 *   EXTI3_IRQn  (IRQ 9)   — line 3
 *   EXTI4_IRQn  (IRQ 10)  — line 4
 *   EXTI9_5_IRQn  (IRQ 23)  — lines 5–9
 *   EXTI15_10_IRQn (IRQ 40) — lines 10–15
 */

GPIO::IRQState* GPIO::_find_or_alloc_irq(uint8_t pin)
{
    for (uint8_t i = 0; i < RTT_GPIO_MAX_IRQ; i++) {
        if (_irq_state[i].in_use && _irq_state[i].pin == pin) {
            return &_irq_state[i];
        }
    }
    for (uint8_t i = 0; i < RTT_GPIO_MAX_IRQ; i++) {
        if (!_irq_state[i].in_use) {
            _irq_state[i].pin = pin;
            _irq_state[i].in_use = true;
            return &_irq_state[i];
        }
    }
    return nullptr;
}

void GPIO::_irq_trampoline(void *args)
{
    IRQState *st = (IRQState *)args;
    if (!st) return;

    st->isr_count++;

    if (st->isr_fn) {
        /* Read pin state directly from IDR */
        uint8_t port = _PIN_PORT(st->pin);
        uint8_t bit  = _PIN_BIT(st->pin);
        bool state = (_gpio_port(port)->IDR >> bit) & 1U;
        uint32_t ts = AP_HAL::micros();
        st->isr_fn(st->pin, state, ts);
    } else if (st->simple_fn) {
        st->simple_fn();
    }
}

/* Convert AP_HAL interrupt trigger mode to EXTI edge bits */
static inline void _exti_config_edge(uint8_t pin_bit,
                                     AP_HAL::GPIO::INTERRUPT_TRIGGER_TYPE mode)
{
    switch (mode) {
    case AP_HAL::GPIO::INTERRUPT_RISING:
        EXTI->RTSR |=  (1UL << pin_bit);
        EXTI->FTSR &= ~(1UL << pin_bit);
        break;
    case AP_HAL::GPIO::INTERRUPT_FALLING:
        EXTI->RTSR &= ~(1UL << pin_bit);
        EXTI->FTSR |=  (1UL << pin_bit);
        break;
    case AP_HAL::GPIO::INTERRUPT_BOTH:
        EXTI->RTSR |= (1UL << pin_bit);
        EXTI->FTSR |= (1UL << pin_bit);
        break;
    default:
        EXTI->RTSR &= ~(1UL << pin_bit);
        EXTI->FTSR &= ~(1UL << pin_bit);
        break;
    }
}

/* Map EXTI line number (0-15) to NVIC IRQn */
static IRQn_Type _exti_line_to_irqn(uint8_t line)
{
    if (line <= 4) {
        return (IRQn_Type)(EXTI0_IRQn + line);
    } else if (line <= 9) {
        return EXTI9_5_IRQn;
    } else {
        return EXTI15_10_IRQn;
    }
}

/* Forward declaration of friend dispatch function */
namespace RTT { void _rtt_gpio_exti_dispatch(uint8_t line); }

/* Common EXTI IRQ dispatcher: find which pin (0-15) in this IRQ group fired */
static void _exti_irq_handler(uint8_t line_first, uint8_t line_last)
{
    uint32_t pr = EXTI->PR;

    for (uint8_t line = line_first; line <= line_last; line++) {
        uint32_t mask = 1UL << line;
        if (pr & mask) {
            /* Clear pending bit by writing 1 */
            EXTI->PR = mask;
            _rtt_gpio_exti_dispatch(line);
        }
    }
}

/* EXTI dispatch — friend of GPIO, accesses private _irq_state.
 * Must be in RTT namespace so friend declaration in GPIO class matches. */
namespace RTT {
void _rtt_gpio_exti_dispatch(uint8_t line)
{
    for (uint8_t i = 0; i < RTT_GPIO_MAX_IRQ; i++) {
        if (GPIO::_irq_state[i].in_use &&
            (_PIN_BIT(GPIO::_irq_state[i].pin) == line)) {
            GPIO::_irq_trampoline(&GPIO::_irq_state[i]);
            break;
        }
    }
}
} /* namespace RTT */

using RTT::_rtt_gpio_exti_dispatch;

/* EXTI IRQ handlers — provide strong definitions to override CMSIS weak stubs */
extern "C" {

void EXTI0_IRQHandler(void)    { _exti_irq_handler(0, 0); }
void EXTI1_IRQHandler(void)    { _exti_irq_handler(1, 1); }
void EXTI2_IRQHandler(void)    { _exti_irq_handler(2, 2); }
void EXTI3_IRQHandler(void)    { _exti_irq_handler(3, 3); }
void EXTI4_IRQHandler(void)    { _exti_irq_handler(4, 4); }
void EXTI9_5_IRQHandler(void)  { _exti_irq_handler(5, 9); }
void EXTI15_10_IRQHandler(void){ _exti_irq_handler(10, 15); }

} /* extern "C" */

bool GPIO::attach_interrupt(uint8_t pin,
                            irq_handler_fn_t fn,
                            INTERRUPT_TRIGGER_TYPE mode)
{
    if (pin >= 176) return false;

    if (mode == INTERRUPT_NONE || fn == nullptr) {
        /* Detach: disable EXTI line, NVIC, and release IRQ state */
        for (uint8_t i = 0; i < RTT_GPIO_MAX_IRQ; i++) {
            if (_irq_state[i].in_use && _irq_state[i].pin == pin) {
                uint8_t bit = _PIN_BIT(pin);
                /* Disable interrupt mask */
                EXTI->IMR &= ~(1UL << bit);
                /* Clear edge triggers */
                EXTI->RTSR &= ~(1UL << bit);
                EXTI->FTSR &= ~(1UL << bit);
                /* Clear pending */
                EXTI->PR = (1UL << bit);
                /* Disable NVIC if this is the only active line in this group */
                IRQn_Type irqn = _exti_line_to_irqn(bit);
                bool still_active = false;
                for (uint8_t j = 0; j < RTT_GPIO_MAX_IRQ; j++) {
                    if (_irq_state[j].in_use && j != i &&
                        _exti_line_to_irqn(_PIN_BIT(_irq_state[j].pin)) == irqn) {
                        still_active = true;
                        break;
                    }
                }
                if (!still_active) {
                    NVIC_DisableIRQ(irqn);
                }
                _irq_state[i].in_use = false;
                _irq_state[i].isr_fn = nullptr;
                _irq_state[i].simple_fn = nullptr;
                return true;
            }
        }
        return fn == nullptr;
    }

    IRQState *st = _find_or_alloc_irq(pin);
    if (!st) return false;

    /* Reject double-attach (ChibiOS semantics: pin already has a handler) */
    if (st->isr_fn != nullptr || st->simple_fn != nullptr) {
        return false;
    }

    st->isr_fn = fn;
    st->simple_fn = nullptr;

    uint8_t port = _PIN_PORT(pin);
    uint8_t bit  = _PIN_BIT(pin);

    _gpio_clk_enable(port);

    /* Set pin to INPUT mode, no pull */
    GPIO_TypeDef *gpio = _gpio_port(port);
    gpio->MODER &= ~(3UL << (bit * 2));
    gpio->PUPDR &= ~(3UL << (bit * 2));
    __DSB();

    /* Enable SYSCFG clock (APB2) — needed for EXTICR access */
    RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
    (void)RCC->APB2ENR;

    /* Route EXTI line to the correct GPIO port via SYSCFG EXTICR */
    uint8_t exti_idx  = bit >> 2;           /* 0..3 */
    uint8_t exti_pos  = (bit & 3U) * 4U;    /* 0, 4, 8, 12 */
    uint32_t exti_mask = ~(0xFU << exti_pos);
    SYSCFG->EXTICR[exti_idx] = (SYSCFG->EXTICR[exti_idx] & exti_mask)
                              | ((uint32_t)port << exti_pos);

    /* Configure edge trigger */
    _exti_config_edge(bit, mode);

    /* Clear any pending interrupt on this line */
    EXTI->PR = (1UL << bit);

    /* Unmask interrupt in EXTI */
    EXTI->IMR |= (1UL << bit);

    /* Enable NVIC */
    NVIC_SetPriority(_exti_line_to_irqn(bit), 5);  /* mid-low priority */
    NVIC_EnableIRQ(_exti_line_to_irqn(bit));

    return true;
}

bool GPIO::attach_interrupt(uint8_t pin, AP_HAL::Proc fn,
                            INTERRUPT_TRIGGER_TYPE mode)
{
    if (pin >= 176) return false;

    if (mode == INTERRUPT_NONE || fn == nullptr) {
        /* Detach: same as above */
        for (uint8_t i = 0; i < RTT_GPIO_MAX_IRQ; i++) {
            if (_irq_state[i].in_use && _irq_state[i].pin == pin) {
                uint8_t bit = _PIN_BIT(pin);
                EXTI->IMR &= ~(1UL << bit);
                EXTI->RTSR &= ~(1UL << bit);
                EXTI->FTSR &= ~(1UL << bit);
                EXTI->PR = (1UL << bit);
                IRQn_Type irqn = _exti_line_to_irqn(bit);
                bool still_active = false;
                for (uint8_t j = 0; j < RTT_GPIO_MAX_IRQ; j++) {
                    if (_irq_state[j].in_use && j != i &&
                        _exti_line_to_irqn(_PIN_BIT(_irq_state[j].pin)) == irqn) {
                        still_active = true;
                        break;
                    }
                }
                if (!still_active) {
                    NVIC_DisableIRQ(irqn);
                }
                _irq_state[i].in_use = false;
                _irq_state[i].isr_fn = nullptr;
                _irq_state[i].simple_fn = nullptr;
                return true;
            }
        }
        return fn == nullptr;
    }

    IRQState *st = _find_or_alloc_irq(pin);
    if (!st) return false;

    if (st->isr_fn != nullptr || st->simple_fn != nullptr) {
        return false;
    }

    st->isr_fn = nullptr;
    st->simple_fn = fn;

    uint8_t port = _PIN_PORT(pin);
    uint8_t bit  = _PIN_BIT(pin);

    _gpio_clk_enable(port);

    GPIO_TypeDef *gpio = _gpio_port(port);
    gpio->MODER &= ~(3UL << (bit * 2));
    gpio->PUPDR &= ~(3UL << (bit * 2));
    __DSB();

    RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
    (void)RCC->APB2ENR;

    uint8_t exti_idx  = bit >> 2;
    uint8_t exti_pos  = (bit & 3U) * 4U;
    uint32_t exti_mask = ~(0xFU << exti_pos);
    SYSCFG->EXTICR[exti_idx] = (SYSCFG->EXTICR[exti_idx] & exti_mask)
                              | ((uint32_t)port << exti_pos);

    _exti_config_edge(bit, mode);

    EXTI->PR = (1UL << bit);
    EXTI->IMR |= (1UL << bit);

    NVIC_SetPriority(_exti_line_to_irqn(bit), 5);
    NVIC_EnableIRQ(_exti_line_to_irqn(bit));

    return true;
}

/* ---------------------------------------------------------------------------
 * valid_pin, pin_to_servo_channel, wait_pin, timer_tick, arming_checks
 * ------------------------------------------------------------------------- */

bool GPIO::valid_pin(uint8_t pin) const
{
    return pin < 176;
}

bool GPIO::pin_to_servo_channel(uint8_t pin, uint8_t &servo_ch) const
{
    /* Compact lookup: only the 6 main FMU outputs */
    static const struct { uint8_t gpio_pin; uint8_t ch; } map[] = {
        { 4*16+14, 0 },  // PE14 → CH1
        { 0*16+10, 1 },  // PA10 → CH2
        { 4*16+11, 2 },  // PE11 → CH3
        { 4*16+9,  3 },  // PE9  → CH4
        { 3*16+13, 4 },  // PD13 → CH5
        { 3*16+14, 5 },  // PD14 → CH6
    };
    for (const auto &m : map) {
        if (m.gpio_pin == pin) {
            servo_ch = m.ch;
            return true;
        }
    }
    return false;
}

bool GPIO::wait_pin(uint8_t pin, INTERRUPT_TRIGGER_TYPE mode, uint32_t timeout_us)
{
    if (!valid_pin(pin)) return false;

    /* Clamp timeout: max 30ms to match ChibiOS constraint */
    if (timeout_us == 0 || timeout_us > 30000U) {
        timeout_us = 30000U;
    }

    /* Ensure pin is in input mode */
    {
        uint8_t port = _PIN_PORT(pin);
        uint8_t bit  = _PIN_BIT(pin);
        GPIO_TypeDef *gpio = _gpio_port(port);
        _gpio_clk_enable(port);
        gpio->MODER &= ~(3UL << (bit * 2));
        gpio->PUPDR &= ~(3UL << (bit * 2));
        __DSB();
    }

    uint64_t start = AP_HAL::micros64();
    uint8_t initial = read(pin);

    while (true) {
        uint8_t current = read(pin);
        bool triggered = false;
        switch (mode) {
        case INTERRUPT_RISING:   triggered = (current && !initial); break;
        case INTERRUPT_FALLING:  triggered = (!current && initial); break;
        case INTERRUPT_BOTH:     triggered = (current != initial); break;
        default: return false;
        }
        if (triggered) return true;
        initial = current;

        if (timeout_us != 0 && (AP_HAL::micros64() - start) >= timeout_us) {
            return false;
        }
        rt_thread_mdelay(1);
    }
}

void GPIO::timer_tick(void)
{
    const uint32_t ISR_FLOOD_THRESHOLD = 1000;
    _isr_flood_detected = false;

    for (uint8_t i = 0; i < RTT_GPIO_MAX_IRQ; i++) {
        if (!_irq_state[i].in_use) continue;
        uint32_t delta = _irq_state[i].isr_count - _irq_state[i].last_isr_count;
        _irq_state[i].last_isr_count = _irq_state[i].isr_count;
        if (delta > ISR_FLOOD_THRESHOLD) {
            _isr_flood_detected = true;
        }
    }
}

bool GPIO::arming_checks(size_t buflen, char *buffer) const
{
    if (_isr_flood_detected) {
        if (buflen > 0 && buffer) {
            snprintf(buffer, buflen, "GPIO ISR flood detected");
        }
        return false;
    }
    return true;
}

/* ---------------------------------------------------------------------------
 * get_mode / set_mode — read/write STM32 MODER register directly.
 * Pin number follows RT-Thread convention: port*16 + bit.
 * Returns raw MODER 2-bit field: 0=input, 1=output, 2=AF, 3=analog.
 * ------------------------------------------------------------------------- */

bool GPIO::get_mode(uint8_t pin, uint32_t &mode)
{
    if (pin >= 176) return false;
    uint8_t port = _PIN_PORT(pin);
    uint8_t bit  = _PIN_BIT(pin);
    GPIO_TypeDef *gpio = _gpio_port(port);
    mode = (gpio->MODER >> (bit * 2)) & 0x03U;
    return true;
}

void GPIO::set_mode(uint8_t pin, uint32_t mode)
{
    if (pin >= 176) return;
    uint8_t port = _PIN_PORT(pin);
    uint8_t bit  = _PIN_BIT(pin);
    GPIO_TypeDef *gpio = _gpio_port(port);
    uint32_t val = gpio->MODER;
    val &= ~(0x03U << (bit * 2));
    val |= (mode & 0x03U) << (bit * 2);
    gpio->MODER = val;
    __DSB();
}

void GPIO::set_af(uint8_t pin, uint8_t af_num)
{
    if (pin >= 176) return;
    uint8_t port = _PIN_PORT(pin);
    uint8_t bit  = _PIN_BIT(pin);
    GPIO_TypeDef *gpio = _gpio_port(port);
    _gpio_clk_enable(port);

    if (bit < 8) {
        /* AFR[0]: low 8 pins, 4 bits per pin */
        uint32_t pos = bit * 4;
        gpio->AFR[0] = (gpio->AFR[0] & ~(0xFU << pos)) | ((uint32_t)af_num << pos);
    } else {
        /* AFR[1]: high 8 pins, 4 bits per pin */
        uint32_t pos = (bit - 8) * 4;
        gpio->AFR[1] = (gpio->AFR[1] & ~(0xFU << pos)) | ((uint32_t)af_num << pos);
    }

    /* Set MODER to alternate function mode (2) */
    gpio->MODER = (gpio->MODER & ~(3UL << (bit * 2))) | (2UL << (bit * 2));
    __DSB();
}
