/*
 * This file is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * SD card support for AP_HAL_RTT.
 *
 * Uses RTT's DFS (Device File System) layer to mount elmfat (FatFS)
 * on top of the SDIO block device (sd0) provided by drv_sdio.c in the
 * STM32 BSP.
 *
 * ChibiOS Reference: libraries/AP_HAL_ChibiOS/sdcard.cpp
 *   - SDMMC path (HAL_USE_SDC): sdcStart() / sdcConnect() / f_mount()
 *   - RTT equivalent:   rt_device_find("sd0") / dfs_mount("sd0", ...)
 *
 * Architecture difference (ADR-005):
 *   ChibiOS manages the SDMMC controller directly via its SDC HAL driver.
 *   RTT relies on the BSP's drv_sdio.c which registers an sd0 block device
 *   using RT-Thread's MMCSD/SDIO framework.
 *   Both achieve the same result: a mounted FAT filesystem on the SD card.
 *
 * DMA write optimization (ADR-011, P4-3):
 *   RTT drv_sdio.c already uses DMA for both reads and writes via system DMA2
 *   (DMA2_Stream6/Channel_4 for TX, DMA2_Stream3/Channel_4 for RX), configured
 *   with DMA_PFCTRL (peripheral flow control), FIFO mode at full threshold, and
 *   INCR4 bursts.
 *
 *   The write path uses a bounce buffer (cache_buf in .sram1_bss, MPU-mapped
 *   non-cacheable) for DMA coherence.  As of P4-3 the bounce buffer was
 *   increased from 4KB to 16KB, allowing AP_Logger's typical 4-16KB writes to
 *   complete in a single DMA transaction instead of 1-4 smaller ones.
 *
 *   ChibiOS reference: SDC driver uses SDMMC internal DMA (IDMA) with a 4KB
 *   bouncebuffer.  Both achieve DMA writes; RTT uses system DMA which shares
 *   the DMA2 bus, while ChibiOS uses the tighter SDMMC IDMA path.
 *
 * NOTE: On RTT, the BSP (rt_board_init.c) mounts the SD card at "/" during
 * boot via sd_card_mount_sync().  AP_Filesystem uses the POSIX backend
 * to access the filesystem at standard paths (/APM/LOGS/, etc.).
 * This file provides the ChibiOS-compatible API (sdcard_init/stop/retry)
 * for code that calls these functions directly.
 */
#include <rtthread.h>
#include <board.h>
#include <dfs_fs.h>
#include <dfs_file.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <string.h>
#include <errno.h>

#include <AP_BoardConfig/AP_BoardConfig.h>

extern const AP_HAL::HAL& hal;

/* mount point on the RTT virtual filesystem */
#define SD_CARD_MOUNT_POINT   "/sdcard"

/* SD card power control pin (PG7 on CUAV V5 = VDD_3V3_SD_CARD_EN).
 * Generated by hwdef.py from the "PG7 VDD_3V3_SD_CARD_EN OUTPUT HIGH"
 * line in hwdef.dat. */
#ifndef HAL_GPIO_SD_CARD_PWR_PIN
#ifdef HAL_GPIO_VDD_3V3_SD_CARD_EN_PIN
#define HAL_GPIO_SD_CARD_PWR_PIN HAL_GPIO_VDD_3V3_SD_CARD_EN_PIN
#else
/* Fallback for boards that don't generate the macro */
#define HAL_GPIO_SD_CARD_PWR_PIN GET_PIN(G, 7)
#endif
#endif

/* Block device names to search — ordered by preference */
static const char * const _sd_dev_names[] = { "sd0", "sd" };

static bool _sdcard_running;

/*
 * Find the SD card block device by trying common device names.
 * Returns the device pointer, or NULL if not found.
 */
static rt_device_t _find_sd_dev(void)
{
    for (size_t i = 0; i < sizeof(_sd_dev_names) / sizeof(_sd_dev_names[0]); i++) {
        rt_device_t dev = rt_device_find(_sd_dev_names[i]);
        if (dev != NULL) {
            return dev;
        }
    }
    return NULL;
}

/*
 * Initialise microSD card if available.
 *
 * Called during AP_BoardConfig initialisation (via BRD_SD_SLOWDOWN
 * parameter handling). Also called from sdcard_retry().
 *
 * Returns true on success, false on failure.
 *
 * ChibiOS Reference: sdcard.cpp:55-156
 *   The ChibiOS path does three things:
 *     1. sdcStart(&sdcd, &sdcconfig)  — start SDMMC peripheral
 *     2. sdcConnect(&sdcd)             — negotiate with card
 *     3. f_mount(&SDC_FS, "/", 1)      — mount FATFS
 *   On RTT, steps 1-2 are handled by drv_sdio.c internally (called
 *   during board init).  We only need to:
 *     1. Power on the card (if we have a power pin)
 *     2. Wait for the sd0 block device to appear
 *     3. Mount via dfs_mount()
 *
 *   The board init code (sd_card_mount_sync / sdcard_port.c) may have
 *   already mounted the card.  Detect this by checking whether the
 *   mount point directory is non-empty.
 */
bool sdcard_init(void)
{
    if (_sdcard_running) {
        return true;
    }

    /* Power on the SD card slot.  If the board init already did this,
     * setting the pin again is harmless (GPIO write is idempotent). */
    rt_pin_mode(HAL_GPIO_SD_CARD_PWR_PIN, PIN_MODE_OUTPUT);
    rt_pin_write(HAL_GPIO_SD_CARD_PWR_PIN, PIN_HIGH);
    rt_thread_mdelay(200);

    /* Check whether the board init code already mounted the card.
     * We do a quick stat on the mount point — if the APM directory
     * already exists, the card was mounted early. */
    struct stat st;
    if (stat(SD_CARD_MOUNT_POINT "/APM", &st) == 0 && S_ISDIR(st.st_mode)) {
        rt_kprintf("[sdcard] SD card already mounted at %s (by board init)\n",
                   SD_CARD_MOUNT_POINT);
        _sdcard_running = true;
        return true;
    }

    /* Also check the root mount point (board init may mount "/") */
    if (stat("/APM", &st) == 0 && S_ISDIR(st.st_mode)) {
        rt_kprintf("[sdcard] SD card already mounted at / (by board init)\n");
        _sdcard_running = true;
        /* /APM dirs already exist in this case */
        return true;
    }

    /* Retry loop — match ChibiOS 3-try behaviour */
    const uint8_t tries = 3;
    for (uint8_t i = 0; i < tries; i++) {
        if (i > 0) {
            rt_thread_mdelay(300);
        }

        rt_device_t sd_dev = _find_sd_dev();
        if (sd_dev == NULL) {
            rt_kprintf("[sdcard] attempt %u: no block device found\n",
                       (unsigned)(i + 1));
            continue;
        }

        /* Create mount point directory */
        mkdir(SD_CARD_MOUNT_POINT, 0x777);

        /* Mount elmfat (ChaN's FatFS) on the block device */
        int ret = dfs_mount(_sd_dev_names[0], SD_CARD_MOUNT_POINT,
                            "elm", 0, 0);
        if (ret == 0) {
            rt_kprintf("[sdcard] mounted %s on %s (attempt %u)\n",
                       _sd_dev_names[0], SD_CARD_MOUNT_POINT,
                       (unsigned)(i + 1));
            _sdcard_running = true;

            /* Create ArduPilot directory structure on the card */
            mkdir(SD_CARD_MOUNT_POINT "/APM", 0x777);
            mkdir(SD_CARD_MOUNT_POINT "/APM/LOGS", 0x777);
            mkdir(SD_CARD_MOUNT_POINT "/APM/TERRAIN", 0x777);
            mkdir(SD_CARD_MOUNT_POINT "/APM/STORAGE", 0x777);

            return true;
        }

        rt_kprintf("[sdcard] attempt %u: dfs_mount(%s) failed: %d\n",
                   (unsigned)(i + 1), _sd_dev_names[0], ret);
    }

    _sdcard_running = false;
    return false;
}

/*
 * Stop the SD card interface — unmount and power down.
 *
 * Called before remount with a different speed, or at shutdown.
 *
 * ChibiOS Reference: sdcard.cpp:161-185
 */
void sdcard_stop(void)
{
    if (!_sdcard_running) {
        return;
    }

    /* Unmount the filesystem */
    int ret = dfs_unmount(SD_CARD_MOUNT_POINT);
    if (ret != 0) {
        rt_kprintf("[sdcard] unmount failed: %d (ignored)\n", ret);
    }

    /* Power down the SD card slot */
    rt_pin_write(HAL_GPIO_SD_CARD_PWR_PIN, PIN_LOW);
    rt_kprintf("[sdcard] stopped\n");

    _sdcard_running = false;
}

/*
 * Retry SD card init.
 *
 * Called periodically from the main loop when the SD card was not
 * previously mounted.  Creates the APM directory structure if the
 * init succeeds.
 *
 * ChibiOS Reference: sdcard.cpp:187-201
 */
bool sdcard_retry(void)
{
    if (!_sdcard_running) {
        if (sdcard_init()) {
            /* Already creates APM dirs inside sdcard_init() */
            return true;
        }
    }
    return _sdcard_running;
}
