/*
 * AP_HAL_RTT — WSPI (QuadSPI/OctoSPI) device driver
 * Register-level polling port from ChibiOS WSPIDevice.
 *
 * Reference: libraries/AP_HAL_ChibiOS/WSPIDevice.cpp
 * Reference: modules/ChibiOS/os/hal/ports/STM32/LLD/QUADSPIv1/hal_wspi_lld.c
 *
 * ChibiOS uses DMA for send/receive + ChibiOS HAL mutex for bus locking.
 * This implementation uses register-level polling (no DMA) and RTT::Semaphore.
 *
 * CUAV V5 (STM32F767): QUADSPI @ 0xA0001000
 * Pixhawk6C Mini (STM32H743): OCTOSPI — TODO (stubs provided)
 *
 * Device table comes from HAL_WSPI_DEVICE_LIST if generated by hwdef,
 * otherwise device_table is empty (no WSPI devices registered).
 */

#include "WSPIDevice.h"
#include <AP_HAL/AP_HAL.h>
#include <AP_Math/AP_Math.h>
#include <AP_HAL/utility/OwnPtr.h>
#include <cstring>
#include <rtthread.h>
#include "Scheduler.h"

#ifdef STM32F767xx
#include <stm32f7xx.h>
#ifndef QUADSPI
#define QUADSPI ((QUADSPI_TypeDef *)QUADSPI_BASE)
#endif
#endif

using namespace RTT;

extern const AP_HAL::HAL& hal;

/* ---------------------------------------------------------------------------
 * CSHT mask (shared by both QuadSPI and OctoSPI HAL compatibility levels).
 * -------------------------------------------------------------------------*/
#if defined(STM32_DCR_CSHT)
#define WSPI_DCR_CSHT_MASK   STM32_DCR_CSHT_MASK
#define WSPI_DCR_CSHT(n)     STM32_DCR_CSHT(n)
#define WSPI_DCR_FSIZE_MASK  STM32_DCR_FSIZE_MASK
#define WSPI_DCR_FSIZE(n)    STM32_DCR_FSIZE(n)
#define WSPI_DCR_CK_MODE     STM32_DCR_CK_MODE
#else
/* Fallback: direct STM32 register values */
#define WSPI_DCR_CSHT_MASK   (7U << 8U)
#define WSPI_DCR_CSHT(n)     ((n) << 8U)
#define WSPI_DCR_FSIZE_MASK  (31U << 16U)
#define WSPI_DCR_FSIZE(n)    ((n) << 16U)
#define WSPI_DCR_CK_MODE     (1U << 0U)
#endif

/* DWSPIDEV mode constants (mirror ChibiOS WSPIDEV_MODE1 / MODE3) */
#define WSPIDEV_MODE1 0
#if defined(STM32_DCR_CK_MODE)
#define WSPIDEV_MODE3 STM32_DCR_CK_MODE
#else
#define WSPIDEV_MODE3 (1U << 0U)
#endif

/* CCP AR register — no address phase macro needed */ 

/* ---------------------------------------------------------------------------
 * Local helpers — QuadSPI register-level polling on STM32F7
 * -------------------------------------------------------------------------*/

#if defined(QUADSPI)

/*
 * Return the QUADSPI register block for a given bus index.
 * bus 0 → QUADSPI (the only instance on STM32F7).
 */
static QUADSPI_TypeDef *_qspi_regs_for_bus(uint8_t bus)
{
    (void)bus;
    return QUADSPI;
}

/*
 * AHB clock frequency for computing the QuadSPI prescaler.
 * STM32F767 @ 216 MHz typical.
 */
static uint32_t _qspi_ahb_clock(void)
{
    /* On STM32F7, QuadSPI clock = HCLK (AHB).  Return RCC->CFGR based value. */
    uint32_t sysclk;
    uint32_t pllcfgr = RCC->PLLCFGR;
    uint32_t pllm = pllcfgr & RCC_PLLCFGR_PLLM_Msk;
    if (pllm == 0) pllm = 16;
    uint32_t plln = (pllcfgr & RCC_PLLCFGR_PLLN_Msk) >> RCC_PLLCFGR_PLLN_Pos;
    if (plln == 0) plln = 432;
    uint32_t pllp = ((pllcfgr & RCC_PLLCFGR_PLLP_Msk) >> RCC_PLLCFGR_PLLP_Pos) + 1;
    uint32_t hse = 8000000; /* CUAV V5 uses 8 MHz HSE */
    sysclk = (hse / pllm) * plln / pllp;
    return sysclk;
}

/*
 * Wait for QuadSPI not busy, with timeout.
 * Returns true if ready, false on timeout.
 */
static bool _qspi_wait_not_busy(QUADSPI_TypeDef *qspi)
{
    uint32_t timeout = 100000;
    while ((qspi->SR & QUADSPI_SR_BUSY) && --timeout) {
        __NOP();
    }
    return timeout > 0;
}

/*
 * Wait for Transfer Complete Flag.
 */
static bool _qspi_wait_tcf(QUADSPI_TypeDef *qspi)
{
    uint32_t timeout = 100000;
    while (!(qspi->SR & QUADSPI_SR_TCF) && --timeout) {
        __NOP();
    }
    qspi->FCR = QUADSPI_FCR_CTCF;  /* Clear TCF */
    return timeout > 0;
}

/*
 * Polling command-only transfer (no data phase).
 */
static bool _qspi_command(QUADSPI_TypeDef *qspi,
                          const AP_HAL::Device::CommandHeader *cmdp)
{
    /* The ChibiOS workaround for D1 (command-only with no address/alt)
     * uses ABR to send the command.  For simplicity, we always set DLR=0
     * and write CCR.  The hardware handles the rest. */
    if (!_qspi_wait_not_busy(qspi)) {
        return false;
    }

    qspi->DLR = 0;
    /* Clear FCR flags */
    qspi->FCR = QUADSPI_FCR_CTCF | QUADSPI_FCR_CTEF;

    /* Determine if the cfg has address mode */
    const uint32_t addr_mode = cmdp->cfg & (3U << 10U);
    if (addr_mode != 0) {
        qspi->AR = cmdp->addr;
    }

    /* CCR triggers the transfer */
    qspi->ABR = cmdp->alt;
    qspi->CCR = cmdp->cmd | cmdp->cfg;

    return _qspi_wait_tcf(qspi);
}

/*
 * Polling send (indirect write).  No DMA — write each byte to DR.
 */
static bool _qspi_send(QUADSPI_TypeDef *qspi,
                       const AP_HAL::Device::CommandHeader *cmdp,
                       const uint8_t *data, uint32_t len)
{
    if (len == 0) {
        return _qspi_command(qspi, cmdp);
    }

    if (!_qspi_wait_not_busy(qspi)) {
        return false;
    }

    qspi->DLR = len - 1;
    qspi->FCR = QUADSPI_FCR_CTCF | QUADSPI_FCR_CTEF;

    const uint32_t addr_mode = cmdp->cfg & (3U << 10U);
    if (addr_mode != 0) {
        qspi->AR = cmdp->addr;
    }

    /* CCR triggers the transfer (FMODE defaults to 00 = indirect write) */
    qspi->ABR = cmdp->alt;
    qspi->CCR = cmdp->cmd | cmdp->cfg;

    /* Write each byte to DR, polling FIFO threshold */
    for (uint32_t i = 0; i < len; i++) {
        uint32_t timeout = 100000;
        while (!(qspi->SR & QUADSPI_SR_FTF) && --timeout) {
            __NOP();
        }
        if (timeout == 0) {
            qspi->FCR = QUADSPI_FCR_CTCF | QUADSPI_FCR_CTEF;
            return false;
        }
        *((__IO uint8_t *)&qspi->DR) = data[i];
    }

    /* Wait for completion */
    bool ok = _qspi_wait_tcf(qspi);
    (void)_qspi_wait_not_busy(qspi);
    return ok;
}

/*
 * Polling receive (indirect read).  No DMA — read each byte from DR.
 */
static bool _qspi_recv(QUADSPI_TypeDef *qspi,
                       const AP_HAL::Device::CommandHeader *cmdp,
                       uint8_t *data, uint32_t len)
{
    if (len == 0) {
        return _qspi_command(qspi, cmdp);
    }

    if (!_qspi_wait_not_busy(qspi)) {
        return false;
    }

    qspi->DLR = len - 1;
    qspi->FCR = QUADSPI_FCR_CTCF | QUADSPI_FCR_CTEF;

    const uint32_t addr_mode = cmdp->cfg & (3U << 10U);
    if (addr_mode != 0) {
        qspi->AR = cmdp->addr;
    }

    /* CCR triggers the transfer with FMODE=01 (indirect read) and dummy cycles */
    qspi->ABR = cmdp->alt;
    qspi->CCR = cmdp->cmd | cmdp->cfg |
                (cmdp->dummy << 18U) |   /* DCYC in bits 22:18 */
                (1U << 26U);             /* QUADSPI_CCR_FMODE_0 = indirect read */

    /* Read each byte from DR, polling FIFO threshold */
    for (uint32_t i = 0; i < len; i++) {
        uint32_t timeout = 100000;
        while (!(qspi->SR & QUADSPI_SR_FTF) && --timeout) {
            __NOP();
        }
        if (timeout == 0) {
            qspi->FCR = QUADSPI_FCR_CTCF | QUADSPI_FCR_CTEF;
            return false;
        }
        data[i] = *((__IO uint8_t *)&qspi->DR);
    }

    /* Wait for completion */
    bool ok = _qspi_wait_tcf(qspi);
    (void)_qspi_wait_not_busy(qspi);
    return ok;
}

/*
 * Enter memory-mapped (XIP) mode.
 */
static bool _qspi_enter_mmap(QUADSPI_TypeDef *qspi,
                              const AP_HAL::Device::CommandHeader *cmdp)
{
    if (!_qspi_wait_not_busy(qspi)) {
        return false;
    }

    /* Disable DMA — not used in memory-mapped mode */
    qspi->CR &= ~QUADSPI_CR_DMAEN;

    qspi->DLR = 0;
    qspi->ABR = 0;
    qspi->AR = 0;

    /* FMODE=11 (memory-mapped) with dummy cycles */
    qspi->CCR = cmdp->cmd | cmdp->cfg |
                (cmdp->dummy << 18U) |   /* DCYC */
                (3U << 26U);             /* QUADSPI_CCR_FMODE_1 | QUADSPI_CCR_FMODE_0 */

    return true;
}

/*
 * Exit memory-mapped (XIP) mode.
 */
static bool _qspi_exit_mmap(QUADSPI_TypeDef *qspi)
{
    /* Abort memory-mapped mode */
    qspi->CR |= QUADSPI_CR_ABORT;
    uint32_t timeout = 100000;
    while ((qspi->CR & QUADSPI_CR_ABORT) && --timeout) {
        __NOP();
    }
    /* Re-enable DMA (we didn't use it, but for consistency) */
    qspi->CR |= QUADSPI_CR_DMAEN;
    return timeout > 0;
}

#endif /* defined(QUADSPI) */

/* ---------------------------------------------------------------------------
 * OctoSPI stubs for STM32H7 — TODO: implement register-level OctoSPI
 * -------------------------------------------------------------------------*/
#if !defined(QUADSPI) && !defined(OCTOSPI)
#warning "WSPIDevice: no QuadSPI or OctoSPI peripheral defined — stubs only"
#endif

/* ---------------------------------------------------------------------------
 * Device table — populated from HAL_WSPI_DEVICE_LIST if available
 * -------------------------------------------------------------------------*/

#ifdef HAL_WSPI_DEVICE_LIST
WSPIDesc WSPIDeviceManager::device_table[] = { HAL_WSPI_DEVICE_LIST };
#else
WSPIDesc WSPIDeviceManager::device_table[] = {};
#endif

/* ---------------------------------------------------------------------------
 * WSPIBus implementation
 * -------------------------------------------------------------------------*/

WSPIBus::WSPIBus(uint8_t _bus)
    : DeviceBus(APM_RTT_SPI_PRIORITY)  /* same priority as SPI */
    , bus(_bus)
    , dcr(0)
    , started(false)
    , prescaler(0)
{
}

/* ---------------------------------------------------------------------------
 * WSPIDevice implementation
 * -------------------------------------------------------------------------*/

WSPIDevice::WSPIDevice(WSPIBus &_bus, WSPIDesc &_device_desc)
    : AP_HAL::WSPIDevice()
    , bus(_bus)
    , device_desc(_device_desc)
{
    set_device_bus(_device_desc.bus);

    /* Zero-initialize mode (command header) */
    memset(&mode, 0, sizeof(mode));
}

QUADSPI_TypeDef *WSPIDevice::_qspi_regs()
{
#if defined(QUADSPI)
    return _qspi_regs_for_bus(device_desc.bus);
#else
    return nullptr;
#endif
}

bool WSPIDevice::is_busy()
{
#if defined(QUADSPI)
    QUADSPI_TypeDef *qspi = _qspi_regs();
    if (qspi == nullptr) return false;
    return (qspi->SR & QUADSPI_SR_BUSY) != 0;
#else
    return false;
#endif
}

bool WSPIDevice::acquire_bus(bool acquire)
{
    if (!bus.semaphore.check_owner()) {
        return false;
    }

    if (acquire) {
        /* Take the bus-level semaphore */
        if (!bus.semaphore.take(HAL_SEMAPHORE_BLOCK_FOREVER)) {
            return false;
        }

#if defined(QUADSPI)
        QUADSPI_TypeDef *qspi = _qspi_regs();
        if (qspi == nullptr) {
            bus.semaphore.give();
            return false;
        }

        if (!bus.started) {
            /* Compute DCR from device descriptor */
            bus.dcr = (device_desc.size_pow2 << 16U) |                    /* FSIZE */
                      ((device_desc.ncs_clk_delay - 1U) << 8U) |          /* CSHT */
                      (device_desc.mode & 1U);                            /* CK_MODE */

            /* Compute prescaler from target speed */
            uint32_t ahb_clk = _qspi_ahb_clock();
            uint32_t div = (ahb_clk + device_desc.speed - 1) / device_desc.speed;
            if (div < 2) div = 2;   /* PRESCALER min is 1 → divider = 2 */
            if (div > 257) div = 257;
            bus.prescaler = (uint8_t)(div - 1U);

            /* Enable QUADSPI peripheral clock */
#if defined(STM32F767xx)
            RCC->AHB3ENR |= RCC_AHB3ENR_QSPIEN;
            (void)RCC->AHB3ENR;
#endif

            /* Configure and enable QUADSPI */
            qspi->CR = 0;  /* disable first */
            qspi->DCR = bus.dcr;
            qspi->CR = ((uint32_t)bus.prescaler << QUADSPI_CR_PRESCALER_Pos) |
                       QUADSPI_CR_EN;

            bus.started = true;
        } else {
            /* Re-apply DCR if different — needed when switching devices */
            if (qspi->DCR != bus.dcr) {
                qspi->DCR = bus.dcr;
            }
        }
#endif /* defined(QUADSPI) */
    } else {
        /* Release the bus-level semaphore */
        bus.semaphore.give();
    }

    return true;
}

bool WSPIDevice::transfer(const uint8_t *send, uint32_t send_len,
                          uint8_t *recv, uint32_t recv_len)
{
    if (!acquire_bus(true)) {
        return false;
    }

    bool ret = true;

    /* Build a command header from the stored mode */
    AP_HAL::Device::CommandHeader cmd_hdr;
    cmd_hdr.cmd   = mode.cmd;
    cmd_hdr.cfg   = mode.cfg;
    cmd_hdr.addr  = mode.addr;
    cmd_hdr.alt   = mode.alt;
    cmd_hdr.dummy = mode.dummy;

#if defined(QUADSPI)
    QUADSPI_TypeDef *qspi = _qspi_regs();
    if (qspi == nullptr) {
        acquire_bus(false);
        return false;
    }

    if (send_len == 0 && recv_len == 0) {
        /* Command only */
        ret = _qspi_command(qspi, &cmd_hdr);
    } else if (send_len > 0 && recv_len == 0) {
        /* Send only */
        ret = _qspi_send(qspi, &cmd_hdr, send, send_len);
    } else if (send_len == 0 && recv_len >= 1) {
        /* Receive only */
        ret = _qspi_recv(qspi, &cmd_hdr, recv, recv_len);
    } else {
        /* Combined send+receive not supported by QuadSPI hardware */
        ret = false;
    }
#else
    (void)send;
    (void)send_len;
    (void)recv;
    (void)recv_len;
    ret = false;
#endif

    acquire_bus(false);
    return ret;
}

void WSPIDevice::set_cmd_header(const AP_HAL::Device::CommandHeader& cmd_hdr)
{
    mode.cmd   = cmd_hdr.cmd;
    mode.cfg   = cmd_hdr.cfg;
    mode.addr  = cmd_hdr.addr;
    mode.alt   = cmd_hdr.alt;
    mode.dummy = cmd_hdr.dummy;
}

bool WSPIDevice::enter_xip_mode(void **map_ptr)
{
#if defined(QUADSPI)
    if (!acquire_bus(true)) {
        return false;
    }

    AP_HAL::Device::CommandHeader cmd_hdr;
    cmd_hdr.cmd   = mode.cmd;
    cmd_hdr.cfg   = mode.cfg;
    cmd_hdr.addr  = mode.addr;
    cmd_hdr.alt   = mode.alt;
    cmd_hdr.dummy = mode.dummy;

    QUADSPI_TypeDef *qspi = _qspi_regs();
    if (qspi == nullptr) {
        acquire_bus(false);
        return false;
    }

    bool ret = _qspi_enter_mmap(qspi, &cmd_hdr);
    if (ret && map_ptr != nullptr) {
        /* STM32F7 QuadSPI memory-mapped base address */
        *map_ptr = (void *)0x90000000;
    }

    acquire_bus(false);
    return ret;
#else
    (void)map_ptr;
    return false;
#endif
}

bool WSPIDevice::exit_xip_mode()
{
#if defined(QUADSPI)
    if (!acquire_bus(true)) {
        return false;
    }

    QUADSPI_TypeDef *qspi = _qspi_regs();
    if (qspi == nullptr) {
        acquire_bus(false);
        return false;
    }

    bool ret = _qspi_exit_mmap(qspi);
    acquire_bus(false);
    return ret;
#else
    return false;
#endif
}

/* ---------------------------------------------------------------------------
 * WSPIDeviceManager implementation
 * -------------------------------------------------------------------------*/

AP_HAL::OwnPtr<AP_HAL::WSPIDevice>
WSPIDeviceManager::get_device(const char *name)
{
    /* Find the device in the table */
    uint8_t i;
    for (i = 0; i < ARRAY_SIZE(device_table); i++) {
        if (strcmp(device_table[i].name, name) == 0) {
            break;
        }
    }
    if (i == ARRAY_SIZE(device_table)) {
        return AP_HAL::OwnPtr<AP_HAL::WSPIDevice>(nullptr);
    }

    WSPIDesc &desc = device_table[i];

    /* Find or create the bus */
    WSPIBus *busp;
    for (busp = buses; busp; busp = (WSPIBus *)busp->next) {
        if (busp->bus == desc.bus) {
            break;
        }
    }
    if (busp == nullptr) {
        busp = NEW_NOTHROW WSPIBus(desc.bus);
        if (busp == nullptr) {
            return AP_HAL::OwnPtr<AP_HAL::WSPIDevice>(nullptr);
        }
        busp->next = buses;
        buses = busp;
    }

    return AP_HAL::OwnPtr<AP_HAL::WSPIDevice>(
        NEW_NOTHROW WSPIDevice(*busp, desc));
}

uint8_t WSPIDeviceManager::get_count() const
{
    return ARRAY_SIZE(device_table);
}

const char *WSPIDeviceManager::get_device_name(uint8_t idx) const
{
    if (idx >= ARRAY_SIZE(device_table)) {
        return nullptr;
    }
    return device_table[idx].name;
}
