# for module compiling
import os
Import('RTT_ROOT')
Import('env')
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

env.Append(CPPDEFINES = ['STM32F427xx', 'USE_HAL_DRIVER'])

# Add package include paths so board/application code can find stm32f4xx.h and HAL
for pkg_inc in [
    os.path.join(cwd, 'packages', 'stm32f4_cmsis_driver-latest', 'Include'),
    os.path.join(cwd, 'packages', 'stm32f4_hal_driver-latest', 'Inc'),
]:
    if os.path.isdir(pkg_inc):
        env.Append(CPPPATH=[pkg_inc])

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
