from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('cherryusb-port', src, depend=['RT_CHERRYUSB_DEVICE', 'BSP_USING_USB_DEVICE'], CPPPATH=CPPPATH)
Return('group')
