import os
from building import *

cwd = GetCurrentDir()

# add the general drivers. (Reset_Handler from package startup is expected by link.lds; ensure F7 HAL is linked via package SConscript if used)
src = Glob('board.c')
src += Glob('rt_board_init.c')
src += Glob('CubeMX_Config/Src/stm32f7xx_hal_msp.c')
# STM32F7 Low-Level SPI DMA driver: eliminates HAL busy-wait from DMA ISR
src += Glob('drv_spi_lld.c')
src += Glob('rtt_libc_compat.c')
src += Glob('startup_rtt_override.S')



path = [cwd]
path += [cwd + '/CubeMX_Config/Inc']


group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

# if os.path.isfile(os.path.join(cwd, "ports", 'SConscript')):
#     group = group + SConscript(os.path.join("ports", 'SConscript'))
list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
